package com.aventurece1.game;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
  final Random rnd=new Random(); final Handler h=new Handler(Looper.getMainLooper());
  SharedPreferences prefs; ToneGenerator sfx; AudioTrack music; Bitmap atlas;
  String level="CP", diff="Normal"; final String[] levels={"CP","CE1","CHAMPION"}; final String[] diffs={"Normal","Difficile","Légendaire","Chrono"};
  int score,good,bad,stage,monsterHp,lives,correct,maxGame; boolean paused=false,over=true,inGame=false; long startMs,pauseMs,pausedTotal; Runnable tick;
  TextView scoreV,livesV,monsterHpV,opV,msgV,timerV,inputV; final Button[] choices=new Button[3];

  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("avent_ce1",MODE_PRIVATE);immersive();home();}
  @Override protected void onResume(){super.onResume();immersive();startMusic();}
  @Override protected void onPause(){stopMusic();super.onPause();}
  @Override public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)immersive();}
  @Override protected void onDestroy(){stopTimer();stopMusic();try{if(sfx!=null)sfx.release();}catch(Throwable ignored){}super.onDestroy();}

  void immersive(){try{getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController ctl=getWindow().getInsetsController();if(ctl!=null){ctl.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());ctl.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else getWindow().getDecorView().setSystemUiVisibility(5894);}catch(Throwable ignored){}}
  void safe(Runnable r){try{r.run();}catch(Throwable e){Toast.makeText(this,"Oups : "+e.getClass().getSimpleName(),Toast.LENGTH_LONG).show();home();}}
  int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} int c(String s){return Color.parseColor(s);} int dark(int x){return Color.rgb((int)(Color.red(x)*.7),(int)(Color.green(x)*.7),(int)(Color.blue(x)*.7));}
  GradientDrawable shape(int fill,int stroke,int radius,int sw){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(sw>0)g.setStroke(dp(sw),stroke);return g;}
  LinearLayout root(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER_HORIZONTAL);l.setPadding(dp(10),dp(10),dp(10),dp(18));l.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{c("#20B8F3"),c("#A7EB67")}));return l;}
  ScrollView sc(View v){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.addView(v);return s;}
  TextView tx(String s,float size,int co){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(co);t.setTypeface(Typeface.DEFAULT_BOLD);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(6),dp(8),dp(6));return t;}
  Button btn(String s,int color){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(19);b.setTypeface(Typeface.DEFAULT_BOLD);GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{color,dark(color)});g.setCornerRadius(dp(22));g.setStroke(dp(3),dark(color));b.setBackground(g);b.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)clickFx();return false;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(60));p.setMargins(dp(8),dp(5),dp(8),dp(5));b.setLayoutParams(p);return b;}
  LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(dp(10),dp(10),dp(10),dp(10));l.setBackground(shape(c("#FFF8D8"),c("#E99A1A"),18,3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(8),dp(6),dp(8),dp(6));l.setLayoutParams(p);return l;}
  void set(View v){setContentView(v);immersive();startMusic();}

  Bitmap atlas(){if(atlas==null)atlas=BitmapFactory.decodeResource(getResources(),R.drawable.final_charter);return atlas;}
  int[] box(String n){switch(n){case"home":return new int[]{0,0,405,405};case"level":return new int[]{412,0,304,405};case"difficulty":return new int[]{723,0,278,405};case"settings":return new int[]{1007,0,273,405};case"rules":return new int[]{1284,0,252,405};case"fight1":return new int[]{0,409,262,390};case"fight2":return new int[]{266,409,252,390};case"summary":return new int[]{521,409,218,390};case"fight4":return new int[]{741,409,259,390};case"victory":return new int[]{1003,409,280,390};case"chrono":return new int[]{1286,409,250,390};case"poop":return new int[]{0,801,232,223};case"fart":return new int[]{234,801,229,223};case"zombie":return new int[]{465,801,227,223};case"funny":return new int[]{693,801,241,223};case"chrono_rules":return new int[]{936,801,228,223};default:return new int[]{1165,801,371,223};}}
  ImageView art(String name,int height){int[] q=box(name);Bitmap a=atlas();Bitmap b=Bitmap.createBitmap(a,q[0],q[1],q[2],q[3]);ImageView v=new ImageView(this);v.setImageBitmap(b);v.setScaleType(ImageView.ScaleType.FIT_CENTER);v.setAdjustViewBounds(true);v.setBackgroundColor(Color.TRANSPARENT);v.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(height)));return v;}
  TextView banner(String s){TextView t=tx(s,26,Color.WHITE);t.setShadowLayer(3,0,2,c("#67320C"));t.setBackground(shape(c("#C9792D"),c("#71330D"),16,3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(22),dp(4),dp(22),dp(8));t.setLayoutParams(p);return t;}

  int pi(String k,int d){return prefs.getInt(k,d);} int min(){return pi(level+"_min",0);} int max(){return pi(level+"_max",level.equals("CP")?100:level.equals("CE1")?200:300);} int mm(){return pi(level+"_mult",level.equals("CE1")?5:10);}
  boolean musicOn(){return prefs.getBoolean("music_on",true);} boolean sfxOn(){return prefs.getBoolean("sfx_on",true);}
  void tone(int type,int ms,int volume){if(!sfxOn())return;try{if(sfx==null)sfx=new ToneGenerator(AudioManager.STREAM_MUSIC,volume);sfx.startTone(type,ms);}catch(Throwable ignored){}}
  void clickFx(){tone(ToneGenerator.TONE_PROP_BEEP,45,35);} void correctFx(){tone(ToneGenerator.TONE_PROP_ACK,160,75);} void wrongFx(){tone(ToneGenerator.TONE_PROP_NACK,210,70);} void levelFx(){tone(ToneGenerator.TONE_PROP_BEEP2,280,80);} void victoryFx(){tone(ToneGenerator.TONE_PROP_ACK,350,90);h.postDelayed(()->tone(ToneGenerator.TONE_PROP_BEEP2,400,90),220);}
  short[] musicData(){int sr=11025;double[] ns={523,659,784,659,587,698,880,698,659,784,1047,784};int note=(int)(sr*.28),gap=(int)(sr*.04);short[] d=new short[ns.length*(note+gap)];int p=0;for(double f:ns){for(int i=0;i<note;i++){double e=Math.min(1,Math.min(i/180.0,(note-i)/320.0));d[p++]=(short)(Math.sin(2*Math.PI*f*i/sr)*e*3200);}p+=gap;}return d;}
  void startMusic(){if(!musicOn()){stopMusic();return;}try{if(music!=null&&music.getPlayState()==AudioTrack.PLAYSTATE_PLAYING)return;stopMusic();short[] d=musicData();music=new AudioTrack(AudioManager.STREAM_MUSIC,11025,AudioFormat.CHANNEL_OUT_MONO,AudioFormat.ENCODING_PCM_16BIT,d.length*2,AudioTrack.MODE_STATIC);music.write(d,0,d.length);music.setLoopPoints(0,d.length,-1);music.setVolume(.11f);music.play();}catch(Throwable ignored){}}
  void stopMusic(){try{if(music!=null){music.stop();music.release();}}catch(Throwable ignored){}music=null;}

  void home(){stopTimer();over=true;inGame=false;paused=false;LinearLayout l=root();ImageView hero=art("home",430);hero.setOnTouchListener((v,e)->{if(e.getAction()!=MotionEvent.ACTION_UP)return true;float y=e.getY()/Math.max(1,v.getHeight()),x=e.getX()/Math.max(1,v.getWidth());if(y>.78){if(x<.25)Toast.makeText(this,"Records disponibles dans les niveaux",Toast.LENGTH_SHORT).show();else if(x<.5)settings();else if(x<.75)Toast.makeText(this,"Choisis ton niveau puis ta difficulté pour jouer !",Toast.LENGTH_LONG).show();else{stopMusic();finishAndRemoveTask();}}else levelMenu();return true;});l.addView(hero);TextView hint=tx("Touchez l'illustration pour jouer",16,c("#174D76"));l.addView(hint);set(sc(l));}

  void levelMenu(){LinearLayout l=root();ImageView v=art("level",500);v.setOnTouchListener((z,e)->{if(e.getAction()!=MotionEvent.ACTION_UP)return true;float y=e.getY()/Math.max(1,z.getHeight()),x=e.getX()/Math.max(1,z.getWidth());if(x<.18&&y<.18){home();return true;}if(y>.20&&y<.39){level="CP";difficulty();}else if(y<.57){level="CE1";difficulty();}else if(y<.75){level="CHAMPION";difficulty();}return true;});l.addView(v);Button back=btn("← Retour",c("#2979D6"));back.setOnClickListener(x->home());l.addView(back);set(sc(l));}

  void difficulty(){LinearLayout l=root();l.addView(banner(level));ImageView v=art("difficulty",470);v.setOnTouchListener((z,e)->{if(e.getAction()!=MotionEvent.ACTION_UP)return true;float y=e.getY()/Math.max(1,z.getHeight());if(y<.17){levelMenu();return true;}if(y>.25&&y<.42){diff="Normal";rules();}else if(y<.57){diff="Difficile";rules();}else if(y<.72){diff="Légendaire";rules();}else if(y<.90){diff="Chrono";rules();}return true;});l.addView(v);LinearLayout rec=card();rec.addView(tx("Records de "+level,18,c("#4A2A0C")));for(String d:diffs){String s=d.equals("Chrono")?(prefs.getLong("time_"+level,0)==0?"0 s":seconds(prefs.getLong("time_"+level,0))):String.valueOf(prefs.getInt("record_"+level+"_"+d,0));rec.addView(tx(d+" : "+s,15,c("#17395C")));}l.addView(rec);set(sc(l));}

  LinearLayout settingRow(String label,int value,int step,int minV,int maxV,TextView[] holder){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView lab=tx(label,15,c("#43260D"));r.addView(lab,new LinearLayout.LayoutParams(0,-2,1));TextView val=tx(String.valueOf(value),18,c("#103A62"));val.setTag(value);val.setBackground(shape(Color.WHITE,c("#63A9DB"),10,2));holder[0]=val;Button m=btn("−",c("#2196F3")),p=btn("+",c("#2196F3"));m.setOnClickListener(v->{int n=Math.max(minV,(Integer)val.getTag()-step);val.setTag(n);val.setText(""+n);});p.setOnClickListener(v->{int n=Math.min(maxV,(Integer)val.getTag()+step);val.setTag(n);val.setText(""+n);});r.addView(m,new LinearLayout.LayoutParams(dp(55),dp(48)));r.addView(val,new LinearLayout.LayoutParams(dp(72),dp(48)));r.addView(p,new LinearLayout.LayoutParams(dp(55),dp(48)));return r;}
  void settings(){LinearLayout l=root();l.addView(art("settings",360));LinearLayout audio=card();Switch mu=new Switch(this);mu.setText("🎵 Musique de fond");mu.setTextSize(17);mu.setChecked(musicOn());audio.addView(mu);Switch sf=new Switch(this);sf.setText("🔊 Effets sonores");sf.setTextSize(17);sf.setChecked(sfxOn());audio.addView(sf);mu.setOnCheckedChangeListener((b,on)->{prefs.edit().putBoolean("music_on",on).apply();if(on)startMusic();else stopMusic();});sf.setOnCheckedChangeListener((b,on)->prefs.edit().putBoolean("sfx_on",on).apply());l.addView(audio);Map<String,TextView[]> map=new LinkedHashMap<>();for(String q:levels){LinearLayout box=card();box.addView(tx(q,21,c("#4E2A0C")));TextView[] mn={null},mx={null},mul={null};box.addView(settingRow("Nombre mini",pi(q+"_min",0),5,0,500,mn));box.addView(settingRow("Nombre maxi",pi(q+"_max",q.equals("CP")?100:q.equals("CE1")?200:300),10,10,500,mx));if(!q.equals("CP"))box.addView(settingRow("Maxi multiplication",pi(q+"_mult",q.equals("CE1")?5:10),1,3,10,mul));map.put(q,new TextView[]{mn[0],mx[0],mul[0]});l.addView(box);}Button save=btn("💾 Enregistrer",c("#38C94A"));save.setOnClickListener(v->{SharedPreferences.Editor ed=prefs.edit();for(String q:levels){TextView[] a=map.get(q);int mi=(Integer)a[0].getTag(),ma=Math.max(mi+1,(Integer)a[1].getTag());ed.putInt(q+"_min",mi).putInt(q+"_max",ma);if(a[2]!=null)ed.putInt(q+"_mult",(Integer)a[2].getTag());}ed.apply();levelFx();home();});l.addView(save);Button back=btn("← Retour",c("#2979D6"));back.setOnClickListener(v->home());l.addView(back);set(sc(l));}

  void rules(){LinearLayout l=root();if(diff.equals("Chrono")){l.addView(banner("MODE CHRONO"));l.addView(art("chrono_rules",300));}else l.addView(art("rules",500));Button go=btn("C'est parti !",c("#37C93F"));go.setTextSize(23);go.setOnClickListener(v->safe(this::startGame));l.addView(go);Button back=btn("← Retour",c("#2979D6"));back.setOnClickListener(v->difficulty());l.addView(back);set(sc(l));}

  void startGame(){score=good=bad=0;stage=1;over=false;inGame=true;paused=false;pausedTotal=0;maxGame=diff.equals("Normal")?Math.max(min()+1,(int)(max()*.70)):max();lives=diff.equals("Normal")?10:diff.equals("Chrono")?1:5;startMs=System.currentTimeMillis();showGame();if(diff.equals("Chrono"))startTimer();}
  String fightArt(){if(diff.equals("Chrono"))return"chrono";if(stage==1)return"fight1";if(stage==2)return"fight2";if(stage==4)return"fight4";return"zombie";}
  String monsterName(){return stage==1?"Monstre Caca":stage==2?"Monstre qui pète":stage==3?"Monstre Zombie":"Monstre Rigolo";}
  void showGame(){inGame=true;over=false;monsterHp=5;LinearLayout l=root();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView st=tx("Monstre "+stage+" / 4",17,Color.WHITE);st.setBackground(shape(c("#147BCE"),c("#064E91"),15,2));top.addView(st,new LinearLayout.LayoutParams(0,-2,1));Button q=btn("✕",c("#EF4E43"));q.setOnClickListener(v->leaveGame());top.addView(q,new LinearLayout.LayoutParams(dp(55),dp(48)));l.addView(top);l.addView(art(fightArt(),diff.equals("Chrono")?300:280));LinearLayout hud=card();livesV=tx("",16,c("#B31515"));monsterHpV=tx("",16,c("#B31515"));scoreV=tx("",17,c("#0E4F82"));hud.addView(livesV);hud.addView(monsterHpV);hud.addView(scoreV);timerV=null;if(diff.equals("Chrono")){timerV=tx(formatTime(elapsed()),22,c("#0B5FA8"));hud.addView(timerV);}l.addView(hud);opV=tx("",37,c("#142B43"));opV.setBackground(shape(c("#FFF7CE"),c("#E49A19"),18,3));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(72));op.setMargins(dp(15),dp(4),dp(15),dp(4));opV.setLayoutParams(op);l.addView(opV);msgV=tx("À toi de jouer !",16,c("#69258E"));l.addView(msgV);if(diff.equals("Légendaire"))keypad(l);else choiceButtons(l);if(diff.equals("Chrono")){Button p=btn("⏸ Pause",c("#248FE2"));p.setOnClickListener(v->togglePause(p));l.addView(p);}set(sc(l));hud();nextQuestion();}
  void choiceButtons(LinearLayout l){LinearLayout r=new LinearLayout(this);int[] cs={c("#159DFF"),c("#FFAA10"),c("#ED48A4")};for(int i=0;i<3;i++){final int k=i;choices[i]=btn("",cs[i]);choices[i].setTextSize(24);choices[i].setOnClickListener(v->{Object o=choices[k].getTag();if(o instanceof Integer)submit((Integer)o);});r.addView(choices[i],new LinearLayout.LayoutParams(0,dp(62),1));}l.addView(r);}
  void keypad(LinearLayout l){inputV=tx("—",30,c("#17304A"));inputV.setBackground(shape(Color.WHITE,c("#55A5DA"),15,2));l.addView(inputV);int n=1;for(int y=0;y<3;y++){LinearLayout r=new LinearLayout(this);for(int x=0;x<3;x++){final int k=n++;Button b=btn(""+k,c("#2196F3"));b.setOnClickListener(v->digit(k));r.addView(b,new LinearLayout.LayoutParams(0,dp(55),1));}l.addView(r);}LinearLayout r=new LinearLayout(this);Button z=btn("0",c("#2196F3"));z.setOnClickListener(v->digit(0));r.addView(z,new LinearLayout.LayoutParams(0,dp(55),1));Button e=btn("⌫",c("#EF5350"));e.setOnClickListener(v->{inputV.setTag("");inputV.setText("—");});r.addView(e,new LinearLayout.LayoutParams(0,dp(55),1));l.addView(r);Button val=btn("Valider",c("#35C947"));val.setOnClickListener(v->{String s=inputV.getTag()==null?"":String.valueOf(inputV.getTag());if(!s.isEmpty())submit(Integer.parseInt(s));});l.addView(val);}
  void digit(int k){if(paused||over)return;String s=inputV.getTag()==null?"":String.valueOf(inputV.getTag());if(s.length()<4){s+=k;inputV.setTag(s);inputV.setText(s);}}
  void hud(){StringBuilder a=new StringBuilder(),b=new StringBuilder();for(int i=0;i<lives;i++)a.append("❤️");for(int i=0;i<monsterHp;i++)b.append("❤️");livesV.setText("Vies : "+(a.length()==0?"💔":a));monsterHpV.setText("Monstre : "+(b.length()==0?"💥":b));scoreV.setText(diff.equals("Chrono")?"⚡ Une seule vie":"Score : "+score);}
  int stageMax(){int n=min(),span=Math.max(1,maxGame-n);double f=stage==1?.4:stage==2?.7:1;return Math.max(n+2,n+(int)(span*f));}
  void nextQuestion(){if(over||paused||!inGame)return;int M=stageMax(),N=Math.min(min(),Math.max(0,M-1)),type=rnd.nextInt(level.equals("CP")?2:3);if(type==2&&!multiplication(M))addition(N,M);else if(type==1)soustraction(N,M);else addition(N,M);if(diff.equals("Légendaire")){inputV.setTag("");inputV.setText("—");}else fillChoices(M);}
  void addition(int N,int M){correct=N+rnd.nextInt(Math.max(1,M-N+1));int a=N+rnd.nextInt(Math.max(1,correct-N+1));int b=correct-a;opV.setText(a+" + "+b+" = ?");}
  void soustraction(int N,int M){int cap=Math.min(M,100),a,b,t=0;do{a=N+rnd.nextInt(Math.max(1,cap-N+1));b=N+rnd.nextInt(Math.max(1,cap-N+1));if(b>a){int x=a;a=b;b=x;}t++;}while(a+b>100&&t<1000);if(a+b>100){a=Math.min(100,cap);b=0;}correct=a-b;opV.setText(a+" − "+b+" = ?");}
  boolean multiplication(int M){ArrayList<int[]> list=new ArrayList<>();int mx=Math.max(3,Math.min(10,mm()));for(int a=2;a<=mx;a++)for(int b=3;b<=10;b++)if(a*b<=M)list.add(new int[]{a,b});if(list.isEmpty())return false;int[] x=list.get(rnd.nextInt(list.size()));correct=x[0]*x[1];opV.setText(x[0]+" × "+x[1]+" = ?");return true;}
  void fillChoices(int M){int gi=rnd.nextInt(3);int[] v={-1,-1,-1};v[gi]=correct;for(int i=0;i<3;i++)if(i!=gi){int z;do{int d=1+rnd.nextInt(Math.max(3,Math.min(15,M/10+2)));z=Math.max(0,correct+(rnd.nextBoolean()?d:-d));}while(z==correct||z==v[0]||z==v[1]||z==v[2]);v[i]=z;}for(int i=0;i<3;i++){choices[i].setText(""+v[i]);choices[i].setTag(v[i]);choices[i].setEnabled(true);}}
  void submit(int v){if(over||paused||!inGame)return;boolean ok=v==correct;if(ok){good++;monsterHp--;if(!diff.equals("Chrono"))score+=10;msgV.setText("🐶 ATTAQUE !  Aïe !");correctFx();}else{bad++;lives--;if(!diff.equals("Chrono"))score=Math.max(0,score-5);msgV.setText("👾 ATTAQUE !  Ouille !");wrongFx();}hud();if(!diff.equals("Légendaire"))for(Button b:choices)if(b!=null)b.setEnabled(false);if(lives<=0){over=true;inGame=false;h.postDelayed(()->finishGame(false),450);}else if(monsterHp<=0){inGame=false;h.postDelayed(this::summary,450);}else h.postDelayed(this::nextQuestion,450);}

  void summary(){inGame=false;if(diff.equals("Chrono"))hold();levelFx();LinearLayout l=root();l.addView(art("summary",390));LinearLayout box=card();box.addView(tx("Tu as vaincu le "+monsterName()+" !",20,c("#5B2D0A")));box.addView(tx("✅ Bonnes réponses : "+good+"\n❌ Mauvaises réponses : "+bad+(diff.equals("Chrono")?"\n⏱ "+formatTime(elapsed()):"\n🏆 Score : "+score),17,c("#17304A")));l.addView(box);Button n=btn(stage<4?"Monstre suivant ➜":"Résultat",c("#F2A900"));n.setOnClickListener(v->{if(stage>=4){if(diff.equals("Chrono"))resumeClock();finishGame(true);}else{stage++;if(diff.equals("Chrono"))resumeClock();showGame();}});l.addView(n);Button q=btn("Quitter la partie",c("#EF5350"));q.setOnClickListener(v->home());l.addView(q);set(sc(l));}
  int stars(){return score>190?5:score>=171?4:score>=141?3:score>=100?2:1;}
  void finishGame(boolean win){inGame=false;over=true;long e=elapsed();stopTimer();if(win)victoryFx();else wrongFx();LinearLayout l=root();l.addView(art(win?"victory":"summary",win?470:380));LinearLayout box=card();boolean rec=false;if(diff.equals("Chrono")){long old=prefs.getLong("time_"+level,0);rec=win&&(old==0||e<old);if(rec)prefs.edit().putLong("time_"+level,e).apply();box.addView(tx("Score chrono : "+seconds(e),24,c("#075FA8")));}else{int old=prefs.getInt("record_"+level+"_"+diff,0);rec=score>old;if(rec)prefs.edit().putInt("record_"+level+"_"+diff,score).apply();box.addView(tx("Score final : "+score+" / 200",24,c("#073B66")));StringBuilder s=new StringBuilder();for(int i=0;i<stars();i++)s.append("⭐");box.addView(tx(s.toString(),36,c("#E49A00")));}if(rec)box.addView(tx("🎉 RECORD ! 🎉",27,c("#D84800")));l.addView(box);Button m=btn("Retour au menu",c("#2196F3"));m.setOnClickListener(v->home());l.addView(m);set(sc(l));}

  void startTimer(){stopTimer();tick=new Runnable(){public void run(){if(!over&&!paused&&inGame&&timerV!=null)timerV.setText(formatTime(elapsed()));if(!over)h.postDelayed(this,100);}};h.post(tick);} void stopTimer(){if(tick!=null)h.removeCallbacks(tick);tick=null;}
  long elapsed(){long now=paused?pauseMs:System.currentTimeMillis();return Math.max(0,now-startMs-pausedTotal);} String formatTime(long m){long s=m/1000;return String.format(Locale.FRANCE,"%02d:%02d.%d",s/60,s%60,(m%1000)/100);} String seconds(long m){return String.format(Locale.FRANCE,"%.1f s",m/1000.0);}
  void hold(){if(!paused){paused=true;pauseMs=System.currentTimeMillis();}} void resumeClock(){if(paused){paused=false;pausedTotal+=System.currentTimeMillis()-pauseMs;}}
  void togglePause(Button b){if(over)return;if(!paused){hold();b.setText("▶ Reprendre");if(msgV!=null)msgV.setText("PAUSE");}else{resumeClock();b.setText("⏸ Pause");if(msgV!=null)msgV.setText("C'est reparti !");}}
  void leaveGame(){boolean was=paused;if(diff.equals("Chrono")&&!paused)hold();new AlertDialog.Builder(this).setTitle("Quitter la partie ?").setMessage("La partie en cours sera perdue.").setNegativeButton("Continuer",(d,w)->{if(diff.equals("Chrono")&&!was)resumeClock();immersive();}).setPositiveButton("Quitter",(d,w)->home()).setOnCancelListener(d->{if(diff.equals("Chrono")&&!was)resumeClock();immersive();}).show();}
  @Override public void onBackPressed(){if(inGame&&!over)leaveGame();else home();}
}
