package com.aventurece1.game;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
  final Random rnd=new Random();
  final Handler h=new Handler(Looper.getMainLooper());
  SharedPreferences prefs;
  ToneGenerator tone;
  String level="CP", diff="Normal";
  final String[] levels={"CP","CE1","CHAMPION"};
  final String[] diffs={"Normal","Difficile","Légendaire","Chrono"};
  int score,good,bad,stage,monsterHp,lives,correct,maxGame;
  boolean paused=false,over=true,inGame=false;
  long startMs,pauseMs,pausedTotal;
  Runnable tick;
  TextView scoreV,livesV,monsterHpV,opV,msgV,timerV,inputV;
  ImageView heroV,monsterV;
  final Button[] choices=new Button[3];

  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("avent_ce1",MODE_PRIVATE);immersive();home();}
  @Override protected void onResume(){super.onResume();immersive();}
  @Override public void onWindowFocusChanged(boolean f){super.onWindowFocusChanged(f);if(f)immersive();}

  void immersive(){try{getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController ctl=getWindow().getInsetsController();if(ctl!=null){ctl.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());ctl.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else{getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);}}catch(Throwable ignored){}}
  void safe(Runnable r){try{r.run();}catch(Throwable e){showError(e);}}
  void later(Runnable r,long ms){h.postDelayed(()->safe(r),ms);}
  void showError(Throwable e){stopTimer();over=true;inGame=false;LinearLayout l=root(c("#FFD0D0"),Color.WHITE);l.addView(wood("OUPS !"));l.addView(panelText("Une erreur est survenue.\n"+e.getClass().getSimpleName()+"\n"+String.valueOf(e.getMessage()),17));Button b=gameButton("Retour au menu",c("#2FA8FF"),c("#0873C3"));b.setOnClickListener(v->home());l.addView(b);set(sc(l));}

  int c(String x){return Color.parseColor(x);} int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
  GradientDrawable grad(int a,int b,int radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{a,b});g.setCornerRadius(dp(radius));return g;}
  GradientDrawable shape(int fill,int stroke,int radius,int sw){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));if(sw>0)g.setStroke(dp(sw),stroke);return g;}
  LinearLayout root(int top,int bottom){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER_HORIZONTAL);l.setPadding(dp(12),dp(18),dp(12),dp(22));l.setBackground(grad(top,bottom,0));return l;}
  ScrollView sc(View v){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.addView(v);return s;}
  TextView tx(String s,float z,int co){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(co);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(7),dp(8),dp(7));t.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);return t;}
  TextView wood(String s){TextView t=tx(s,27,Color.WHITE);t.setShadowLayer(3,0,2,c("#6C2D0C"));t.setBackground(shape(c("#C87528"),c("#7A370E"),18,3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(22),dp(5),dp(22),dp(10));t.setLayoutParams(p);return t;}
  LinearLayout panel(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setPadding(dp(12),dp(12),dp(12),dp(12));l.setBackground(shape(c("#FFF8D8"),c("#F0A51A"),20,3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(8),dp(7),dp(8),dp(7));l.setLayoutParams(p);return l;}
  TextView panelText(String s,float z){TextView t=tx(s,z,c("#43260D"));t.setBackground(shape(c("#FFF8D8"),c("#E7A028"),18,2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(8),dp(6),dp(8),dp(6));t.setLayoutParams(p);return t;}
  Button gameButton(String s,int a,int b){Button x=new Button(this);x.setText(s);x.setTextSize(20);x.setTextColor(Color.WHITE);x.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);x.setAllCaps(false);x.setShadowLayer(2,0,1,c("#333333"));GradientDrawable g=grad(a,b,22);g.setStroke(dp(3),dark(a));x.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(dp(10),dp(6),dp(10),dp(6));x.setLayoutParams(p);return x;}
  int dark(int x){return Color.rgb((int)(Color.red(x)*.67),(int)(Color.green(x)*.67),(int)(Color.blue(x)*.67));}
  ImageView img(int res,int height){ImageView x=new ImageView(this);x.setImageResource(res);x.setScaleType(ImageView.ScaleType.CENTER_INSIDE);x.setAdjustViewBounds(true);x.setBackgroundColor(Color.TRANSPARENT);x.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(height)));return x;}
  TextView chip(String s,int color){TextView t=tx(s,16,Color.WHITE);t.setBackground(shape(color,dark(color),20,2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(4),dp(4),dp(4),dp(4));t.setLayoutParams(p);return t;}
  void scenery(LinearLayout l){TextView deco=tx("☁️        🦋     ☀️        🦋        ☁️",19,c("#FFFFFF"));deco.setPadding(0,0,0,0);l.addView(deco);}
  void set(View v){setContentView(v);immersive();}
  int pi(String k,int v){return prefs.getInt(k,v);} int min(){return pi(level+"_min",0);} int max(){return pi(level+"_max",level.equals("CP")?100:level.equals("CE1")?200:300);} int mm(){return pi(level+"_mult",level.equals("CE1")?5:10);}

  void home(){stopTimer();over=true;inGame=false;paused=false;LinearLayout l=root(c("#35BDF4"),c("#8CE879"));scenery(l);l.addView(wood("🌟 AVENTURE CE1 🌟"));ImageView hero=img(R.drawable.rules_hero,210);l.addView(hero);TextView subtitle=tx("Choisis ton niveau",23,c("#073B66"));subtitle.setBackground(shape(c("#FFF6C7"),c("#F3A91C"),18,2));LinearLayout.LayoutParams stp=new LinearLayout.LayoutParams(-1,-2);stp.setMargins(dp(35),0,dp(35),dp(8));subtitle.setLayoutParams(stp);l.addView(subtitle);int[][] cs={{0xFF159DFF,0xFF006ED8},{0xFF4CDA35,0xFF15942D},{0xFFB74DF4,0xFF7624BE}};for(int i=0;i<3;i++){final String q=levels[i];Button b=gameButton((i==2?"👑  ":"⭐  ")+q,cs[i][0],cs[i][1]);b.setTextSize(25);b.setOnClickListener(v->safe(()->{level=q;difficulty();}));l.addView(b);}LinearLayout tools=new LinearLayout(this);Button settings=gameButton("⚙ Paramètres",c("#2FA8FF"),c("#0873C3"));settings.setOnClickListener(v->safe(this::settings));tools.addView(settings,new LinearLayout.LayoutParams(0,dp(58),1));Button quit=gameButton("🚪 Quitter",c("#FF6B61"),c("#D53535"));quit.setOnClickListener(v->{stopTimer();finishAndRemoveTask();});tools.addView(quit,new LinearLayout.LayoutParams(0,dp(58),1));l.addView(tools);set(sc(l));}

  void difficulty(){over=true;inGame=false;LinearLayout l=root(c("#38C3F4"),c("#94E77A"));scenery(l);l.addView(wood(level));LinearLayout box=panel();box.addView(tx("Choisis la difficulté",21,c("#51300E")));int[][] cs={{0xFF4FDE42,0xFF17952D},{0xFFFFA51F,0xFFE15B00},{0xFFB84AF1,0xFF7426B9},{0xFF2DAEF5,0xFF096BBC}};for(int i=0;i<4;i++){final String q=diffs[i];String rec;if(q.equals("Chrono")){long z=prefs.getLong("time_"+level,0);rec="⏱ Meilleur temps : "+(z==0?"0 s":seconds(z));}else rec="🏆 Meilleur score : "+prefs.getInt("record_"+level+"_"+q,0);Button b=gameButton(q+"     "+rec,cs[i][0],cs[i][1]);b.setTextSize(18);b.setOnClickListener(v->safe(()->{diff=q;rules();}));box.addView(b);}l.addView(box);Button back=gameButton("← Retour",c("#667D95"),c("#435469"));back.setOnClickListener(v->home());l.addView(back);set(sc(l));}

  LinearLayout settingRow(String label,int value,int step,int minV,int maxV,TextView[] holder){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(tx(label,16,c("#3A260F")),new LinearLayout.LayoutParams(0,-2,1));Button minus=gameButton("−",c("#2FA8FF"),c("#0873C3"));TextView val=tx(String.valueOf(value),20,c("#17324D"));val.setBackground(shape(Color.WHITE,c("#A5C9E8"),12,2));val.setTag(value);holder[0]=val;Button plus=gameButton("+",c("#2FA8FF"),c("#0873C3"));minus.setOnClickListener(v->{int n=(Integer)val.getTag();n=Math.max(minV,n-step);val.setTag(n);val.setText(String.valueOf(n));});plus.setOnClickListener(v->{int n=(Integer)val.getTag();n=Math.min(maxV,n+step);val.setTag(n);val.setText(String.valueOf(n));});row.addView(minus,new LinearLayout.LayoutParams(dp(56),dp(48)));row.addView(val,new LinearLayout.LayoutParams(dp(72),dp(48)));row.addView(plus,new LinearLayout.LayoutParams(dp(56),dp(48)));return row;}
  void settings(){stopTimer();over=true;inGame=false;LinearLayout l=root(c("#34BDF2"),c("#9BE87D"));scenery(l);l.addView(wood("⚙ PARAMÈTRES"));final Map<String,TextView[]> map=new LinkedHashMap<>();int[] head={c("#2C95F2"),c("#32B74B"),c("#8F3DD8")};for(int i=0;i<levels.length;i++){String q=levels[i];LinearLayout box=panel();TextView hd=tx(q,23,Color.WHITE);hd.setBackground(shape(head[i],dark(head[i]),14,2));box.addView(hd);TextView[] mn={null},mx={null},mul={null};box.addView(settingRow("Nombre mini",pi(q+"_min",0),5,0,500,mn));box.addView(settingRow("Nombre maxi",pi(q+"_max",q.equals("CP")?100:q.equals("CE1")?200:300),10,10,500,mx));if(!q.equals("CP"))box.addView(settingRow("Maxi multiplication",pi(q+"_mult",q.equals("CE1")?5:10),1,3,10,mul));map.put(q,new TextView[]{mn[0],mx[0],mul[0]});l.addView(box);}Button save=gameButton("💾 Enregistrer",c("#43D95A"),c("#168A32"));save.setOnClickListener(v->safe(()->{SharedPreferences.Editor ed=prefs.edit();for(String q:levels){TextView[] a=map.get(q);int mi=(Integer)a[0].getTag(),ma=Math.max(mi+1,(Integer)a[1].getTag());ed.putInt(q+"_min",mi);ed.putInt(q+"_max",ma);if(a[2]!=null)ed.putInt(q+"_mult",(Integer)a[2].getTag());}ed.apply();Toast.makeText(this,"Paramètres enregistrés",Toast.LENGTH_SHORT).show();home();}));l.addView(save);Button back=gameButton("← Retour",c("#667D95"),c("#435469"));back.setOnClickListener(v->home());l.addView(back);set(sc(l));}

  void rules(){over=true;inGame=false;LinearLayout l=root(c("#38C4F5"),c("#92E879"));scenery(l);l.addView(wood(diff.equals("Chrono")?"⏱ MODE CHRONO":"📜 RÈGLES DU JEU"));l.addView(img(R.drawable.rules_hero,205));LinearLayout box=panel();String text=diff.equals("Chrono")?"Bats les 4 monstres le plus vite possible !\n\n⚠ Attention, sois prudent, tu n'as qu'une seule vie.\n\n⏸ Le bouton Pause arrête le chrono.":"Prêt à affronter le monstre ?\n\n✅ Chaque bonne réponse fait gagner 10 points et perdre une vie au monstre.\n\n❌ Chaque mauvaise réponse fait perdre 5 points et une vie.\n\nSi tu n'as plus de vie, le monstre a gagné.";box.addView(tx(text,18,c("#45270E")));l.addView(box);Button go=gameButton("C'est parti !",c("#45DA4C"),c("#168E31"));go.setTextSize(24);go.setOnClickListener(v->safe(this::startGame));l.addView(go);Button back=gameButton("← Retour",c("#667D95"),c("#435469"));back.setOnClickListener(v->difficulty());l.addView(back);set(sc(l));}

  void startGame(){score=good=bad=0;stage=1;over=false;inGame=true;paused=false;pausedTotal=0;maxGame=diff.equals("Normal")?Math.max(min()+1,(int)Math.floor(max()*.70)):max();lives=diff.equals("Normal")?10:diff.equals("Chrono")?1:5;startMs=System.currentTimeMillis();showGame();if(diff.equals("Chrono"))startTimer();}
  int monsterRes(){return stage==1?R.drawable.monster_poop:stage==2?R.drawable.monster_fart:stage==3?R.drawable.monster_zombie:R.drawable.monster_funny;}
  String monsterName(){return stage==1?"Monstre Caca":stage==2?"Monstre qui pète":stage==3?"Monstre Zombie":"Monstre Rigolo";}

  void showGame(){inGame=true;over=false;monsterHp=5;LinearLayout l=root(c("#40C7F3"),c("#86DE66"));LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);TextView badge=chip("Monstre "+stage+" / 4",c("#1878C9"));header.addView(badge,new LinearLayout.LayoutParams(0,-2,1));Button quit=gameButton("✕",c("#FF6B61"),c("#D53535"));quit.setTextSize(18);quit.setContentDescription("Quitter la partie");quit.setOnClickListener(v->leaveGame());header.addView(quit,new LinearLayout.LayoutParams(dp(54),dp(50)));l.addView(header);LinearLayout arena=new LinearLayout(this);arena.setGravity(Gravity.CENTER);LinearLayout left=panel();left.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));heroV=img(R.drawable.heroes,135);left.addView(heroV);livesV=tx("",14,c("#B71C1C"));left.addView(livesV);arena.addView(left);LinearLayout right=panel();right.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));monsterV=img(monsterRes(),135);right.addView(monsterV);right.addView(tx(monsterName(),15,c("#5A2D09")));monsterHpV=tx("",14,c("#B71C1C"));right.addView(monsterHpV);arena.addView(right);l.addView(arena);LinearLayout stats=new LinearLayout(this);scoreV=chip("",c("#0B5E9B"));stats.addView(scoreV,new LinearLayout.LayoutParams(0,-2,1));timerV=null;if(diff.equals("Chrono")){timerV=chip(formatTime(elapsed()),c("#1D75C5"));stats.addView(timerV,new LinearLayout.LayoutParams(0,-2,1));}l.addView(stats);opV=tx("",40,c("#14293B"));opV.setBackground(shape(c("#FFF9D7"),c("#E9A21E"),18,3));LinearLayout.LayoutParams opP=new LinearLayout.LayoutParams(-1,dp(80));opP.setMargins(dp(15),dp(5),dp(15),dp(5));opV.setLayoutParams(opP);l.addView(opV);msgV=tx("À toi de jouer !",17,c("#5B2084"));msgV.setBackground(shape(c("#FFFFFF"),c("#B7D7EA"),15,2));l.addView(msgV);if(diff.equals("Légendaire"))keypad(l);else choiceButtons(l);if(diff.equals("Chrono")){Button pz=gameButton(paused?"▶ Reprendre":"⏸ Pause",c("#29A9F5"),c("#086CBC"));pz.setOnClickListener(v->togglePause(pz));l.addView(pz);}set(sc(l));hud();nextQuestion();}

  void choiceButtons(LinearLayout l){LinearLayout row=new LinearLayout(this);int[] cs={c("#159DFF"),c("#FFB312"),c("#F14AA6")};for(int i=0;i<3;i++){final int n=i;choices[i]=gameButton("",cs[i],dark(cs[i]));choices[i].setTextSize(25);choices[i].setOnClickListener(v->safe(()->{Object o=choices[n].getTag();if(o instanceof Integer)submit((Integer)o);}));row.addView(choices[i],new LinearLayout.LayoutParams(0,dp(65),1));}l.addView(row);}
  void keypad(LinearLayout l){inputV=tx("—",32,c("#222222"));inputV.setBackground(shape(Color.WHITE,c("#7CB9E8"),18,2));l.addView(inputV);int n=1;for(int y=0;y<3;y++){LinearLayout row=new LinearLayout(this);for(int x=0;x<3;x++){final int k=n++;Button b=gameButton(String.valueOf(k),c("#2FA8FF"),c("#0873C3"));b.setOnClickListener(v->digit(k));row.addView(b,new LinearLayout.LayoutParams(0,dp(58),1));}l.addView(row);}LinearLayout row=new LinearLayout(this);Button z=gameButton("0",c("#2FA8FF"),c("#0873C3"));z.setOnClickListener(v->digit(0));row.addView(z,new LinearLayout.LayoutParams(0,dp(58),1));Button e=gameButton("⌫ Effacer",c("#FF9E1C"),c("#D56500"));e.setOnClickListener(v->{inputV.setTag("");inputV.setText("—");});row.addView(e,new LinearLayout.LayoutParams(0,dp(58),1));l.addView(row);Button val=gameButton("✅ VALIDER",c("#42D953"),c("#168E31"));val.setTextSize(24);val.setOnClickListener(v->safe(()->{String s=inputV.getTag()==null?"":String.valueOf(inputV.getTag());if(!s.isEmpty())submit(Integer.parseInt(s));}));l.addView(val);}
  void digit(int k){if(paused||over)return;String s=inputV.getTag()==null?"":String.valueOf(inputV.getTag());if(s.length()<4){s+=k;inputV.setTag(s);inputV.setText(s);}}
  void hud(){StringBuilder a=new StringBuilder(),b=new StringBuilder();for(int i=0;i<lives;i++)a.append("❤️");for(int i=0;i<monsterHp;i++)b.append("❤️");livesV.setText("Vies : "+(a.length()==0?"💔":a));monsterHpV.setText(b.length()==0?"💥":b.toString());scoreV.setText(diff.equals("Chrono")?"⚡ Une seule vie !":"🏆 Score : "+score);}
  int stageMax(){int n=min(),span=Math.max(1,maxGame-n);double f=stage==1?.40:stage==2?.70:1.0;return Math.max(n+2,n+(int)(span*f));}

  void nextQuestion(){if(over||paused||!inGame)return;int M=stageMax(),N=Math.min(min(),Math.max(0,M-1)),type=rnd.nextInt(level.equals("CP")?2:3);if(type==2&&!multiplication(M))addition(N,M);else if(type==1)soustraction(N,M);else addition(N,M);if(diff.equals("Légendaire")){inputV.setTag("");inputV.setText("—");}else fillChoices(M);}
  void addition(int N,int M){correct=N+rnd.nextInt(Math.max(1,M-N+1));int a=N+rnd.nextInt(Math.max(1,correct-N+1));int b=correct-a;opV.setText(a+" + "+b+" = ?");}
  void soustraction(int N,int M){int cap=Math.min(M,100);int a,b,tries=0;do{a=N+rnd.nextInt(Math.max(1,cap-N+1));b=N+rnd.nextInt(Math.max(1,cap-N+1));if(b>a){int t=a;a=b;b=t;}tries++;}while(a+b>100&&tries<1000);if(a+b>100){a=Math.min(cap,100);b=0;}correct=a-b;opV.setText(a+" − "+b+" = ?");}
  boolean multiplication(int M){ArrayList<int[]> list=new ArrayList<>();int maxMult=Math.max(3,Math.min(10,mm()));for(int a=2;a<=maxMult;a++)for(int b=3;b<=10;b++)if(a*b<=M)list.add(new int[]{a,b});if(list.isEmpty())return false;int[] x=list.get(rnd.nextInt(list.size()));correct=x[0]*x[1];opV.setText(x[0]+" × "+x[1]+" = ?");return true;}
  void fillChoices(int M){int goodIndex=rnd.nextInt(3);int[] vals={-1,-1,-1};vals[goodIndex]=correct;for(int i=0;i<3;i++)if(i!=goodIndex){int z,tries=0;do{int delta=1+rnd.nextInt(Math.max(3,Math.min(15,M/10+2)));z=Math.max(0,correct+(rnd.nextBoolean()?delta:-delta));tries++;}while((z==correct||z==vals[0]||z==vals[1]||z==vals[2])&&tries<100);if(z==correct)z=correct+i+1;vals[i]=z;}for(int i=0;i<3;i++){choices[i].setText(String.valueOf(vals[i]));choices[i].setTag(vals[i]);choices[i].setEnabled(true);}}

  void submit(int v){if(over||paused||!inGame)return;boolean ok=v==correct;if(ok){good++;monsterHp--;if(!diff.equals("Chrono"))score+=10;msgV.setText("🐶 ATTAQUE !   👾 Aïe !");sound(true);animate(true);}else{bad++;lives--;if(!diff.equals("Chrono"))score=Math.max(0,score-5);msgV.setText("👾 ATTAQUE !   👧🐶 Ouille !");sound(false);animate(false);}hud();if(!diff.equals("Légendaire"))for(Button b:choices)if(b!=null)b.setEnabled(false);if(lives<=0){over=true;inGame=false;later(()->finishGame(false),450);}else if(monsterHp<=0){inGame=false;later(this::summary,450);}else later(this::nextQuestion,450);}
  void sound(boolean yes){try{if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_MUSIC,65);tone.startTone(yes?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_NACK,160);}catch(Throwable ignored){}}
  void levelSound(){try{if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_MUSIC,70);tone.startTone(ToneGenerator.TONE_PROP_BEEP2,300);}catch(Throwable ignored){}}
  void animate(boolean yes){try{View a=yes?heroV:monsterV,b=yes?monsterV:heroV;a.animate().translationX(yes?dp(16):-dp(16)).setDuration(110).withEndAction(()->a.animate().translationX(0).setDuration(110)).start();b.animate().rotationBy(5).setDuration(90).withEndAction(()->b.animate().rotation(0).setDuration(90)).start();}catch(Throwable ignored){}}

  void summary(){inGame=false;if(diff.equals("Chrono"))hold();levelSound();LinearLayout l=root(c("#44C7F2"),c("#A4E86F"));scenery(l);l.addView(wood("🎉 BRAVO ! 🎉"));l.addView(img(monsterRes(),180));LinearLayout box=panel();box.addView(tx("Tu as vaincu le "+monsterName()+" !",22,c("#6D360F")));box.addView(tx("✅ Bonnes réponses : "+good+"\n❌ Mauvaises réponses : "+bad+(diff.equals("Chrono")?"\n⏱ Temps : "+formatTime(elapsed()):"\n🏆 Score : "+score),18,c("#333333")));l.addView(box);Button nx=gameButton(stage<4?"➡ Monstre suivant":"🏁 Résultat",c("#45D653"),c("#168E31"));nx.setOnClickListener(v->safe(()->{if(stage>=4){if(diff.equals("Chrono"))resumeClock();finishGame(true);}else{stage++;if(diff.equals("Chrono"))resumeClock();showGame();}}));l.addView(nx);Button quit=gameButton("✕ Quitter la partie",c("#FF6B61"),c("#D53535"));quit.setOnClickListener(v->home());l.addView(quit);set(sc(l));}
  int stars(){return score>190?5:score>=171?4:score>=141?3:score>=100?2:1;}
  void finishGame(boolean win){inGame=false;over=true;long e=elapsed();stopTimer();LinearLayout l=root(win?c("#41C9F4"):c("#FF9A9A"),win?c("#A5E76C"):c("#FFD6D6"));scenery(l);l.addView(wood(win?"🌟 INCROYABLE ! 🌟":"💥 PARTIE TERMINÉE"));if(win)l.addView(img(R.drawable.victory_family,225));LinearLayout box=panel();box.addView(tx(win?"Tu as vaincu les 4 monstres !":"Le monstre a gagné",23,win?c("#145B2D"):c("#A51414")));boolean rec=false;if(diff.equals("Chrono")){long old=prefs.getLong("time_"+level,0);rec=win&&(old==0||e<old);if(rec)prefs.edit().putLong("time_"+level,e).apply();box.addView(tx("Score chrono : "+seconds(e),28,c("#075FA8")));}else{int old=prefs.getInt("record_"+level+"_"+diff,0);rec=score>old;if(rec)prefs.edit().putInt("record_"+level+"_"+diff,score).apply();box.addView(tx("Score final : "+score+" / 200",28,c("#073B66")));StringBuilder s=new StringBuilder();for(int i=0;i<stars();i++)s.append("⭐");box.addView(tx(s.toString(),39,c("#E6A300")));}if(rec)box.addView(tx("🎉 RECORD ! 🎉",31,c("#D05A00")));l.addView(box);Button menu=gameButton("🏠 Retour au menu",c("#2FA8FF"),c("#0873C3"));menu.setOnClickListener(v->home());l.addView(menu);set(sc(l));}

  void startTimer(){stopTimer();tick=new Runnable(){public void run(){try{if(!over&&!paused&&inGame&&timerV!=null&&timerV.isAttachedToWindow())timerV.setText(formatTime(elapsed()));if(!over)h.postDelayed(this,100);}catch(Throwable ignored){}}};h.post(tick);}
  void stopTimer(){if(tick!=null)h.removeCallbacks(tick);tick=null;}
  long elapsed(){long now=paused?pauseMs:System.currentTimeMillis();return Math.max(0,now-startMs-pausedTotal);}
  String formatTime(long m){long s=m/1000;return String.format(Locale.FRANCE,"%02d:%02d.%d",s/60,s%60,(m%1000)/100);}
  String seconds(long m){return String.format(Locale.FRANCE,"%.1f s",m/1000.0);}
  void hold(){if(!paused){paused=true;pauseMs=System.currentTimeMillis();}}
  void resumeClock(){if(paused){paused=false;pausedTotal+=System.currentTimeMillis()-pauseMs;}}
  void togglePause(Button b){if(over)return;if(!paused){hold();b.setText("▶ Reprendre");if(msgV!=null)msgV.setText("⏸ PAUSE");}else{resumeClock();b.setText("⏸ Pause");if(msgV!=null)msgV.setText("C'est reparti !");}}
  void leaveGame(){boolean wasPaused=paused;if(diff.equals("Chrono")&&!paused)hold();new AlertDialog.Builder(this).setTitle("Quitter la partie ?").setMessage("La partie en cours sera perdue.").setNegativeButton("Continuer",(d,w)->{if(diff.equals("Chrono")&&!wasPaused)resumeClock();immersive();}).setPositiveButton("Quitter",(d,w)->home()).setOnCancelListener(d->{if(diff.equals("Chrono")&&!wasPaused)resumeClock();immersive();}).show();}

  @Override public void onBackPressed(){if(inGame&&!over)leaveGame();else home();}
  @Override protected void onDestroy(){stopTimer();try{if(tone!=null)tone.release();}catch(Throwable ignored){}super.onDestroy();}
}
