package com.appli.nutristat;
import android.database.sqlite.*;import android.database.*;import android.content.*;import java.time.*;import java.util.*;
public class NutriDb extends SQLiteOpenHelper{
 public static class Nutrients{public double cal,protein,fat,carbs,fiber,sugar;public Nutrients(){}public Nutrients(double a,double b,double c,double d,double e,double f){cal=a;protein=b;fat=c;carbs=d;fiber=e;sugar=f;}public Nutrients scale(double x){return new Nutrients(cal*x,protein*x,fat*x,carbs*x,fiber*x,sugar*x);}public void add(Nutrients n){cal+=n.cal;protein+=n.protein;fat+=n.fat;carbs+=n.carbs;fiber+=n.fiber;sugar+=n.sugar;}}
 public static class Profile{public long id;public String name;public int age;public double weight,cal,protein,fat,carbs,fiber,sugar;public Profile(long id,String n,int a,double w,double c,double p,double f,double g,double fi,double s){this.id=id;name=n;age=a;weight=w;cal=c;protein=p;fat=f;carbs=g;fiber=fi;sugar=s;}public String toString(){return name;}}
 public static class Food{public long id;public String name,brand,categories;public double cal,protein,fat,carbs,fiber,sugar;public Food(long id,String n,String b,String cats,double c,double p,double f,double g,double fi,double s){this.id=id;name=n;brand=b;categories=cats==null?"":cats;cal=c;protein=p;fat=f;carbs=g;fiber=fi;sugar=s;}public String toString(){return name;}}
 public static class Recipe{public long id;public String name;public double portions,cal,protein,fat,carbs,fiber,sugar;public String toString(){return name;}}
 public static class Ingredient{public Food food;public double grams;public Ingredient(Food f,double g){food=f;grams=g;}}
 public static class Meal{public long id;public String date,meal,item,amount,time;public double cal,protein,fat,carbs,fiber,sugar;}
 public static class DayStat{public String date;public Nutrients n;}
 public static class HourStat{public int hour;public Nutrients n;}
 public static class WeightLog{public String date;public double weight;}
 public NutriDb(Context c){super(c,"nutristat.db",null,4);}
 public void onCreate(SQLiteDatabase d){
  d.execSQL("create table profiles(id integer primary key,name text,age integer,weight real,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table foods(id integer primary key,name text,brand text,categories text,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table recipes(id integer primary key,name text,portions real,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table meals(id integer primary key,profile_id integer,date text,time text,meal text,item text,amount text,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table weights(id integer primary key,profile_id integer,date text,weight real,unique(profile_id,date))");
  d.execSQL("insert into profiles values(1,'Utilisateur',30,70,2000,120,70,230,30,50)");seedPoster(d);
 }
 public void onUpgrade(SQLiteDatabase d,int o,int n){ensureSchema(d);seedPoster(d);} public void onOpen(SQLiteDatabase d){super.onOpen(d);if(!d.isReadOnly()){ensureSchema(d);seedPoster(d);}}
 private boolean hasColumn(SQLiteDatabase d,String table,String col){Cursor c=null;try{c=d.rawQuery("pragma table_info("+table+")",null);while(c.moveToNext())if(col.equalsIgnoreCase(c.getString(c.getColumnIndexOrThrow("name"))))return true;}catch(Exception ignored){}finally{if(c!=null)c.close();}return false;}
 private void ensureSchema(SQLiteDatabase d){try{if(!hasColumn(d,"foods","categories"))d.execSQL("alter table foods add column categories text default ''");}catch(Exception ignored){}try{if(!hasColumn(d,"meals","time"))d.execSQL("alter table meals add column time text default '12:00'");}catch(Exception ignored){}try{d.execSQL("update meals set time='12:00' where time is null or trim(time)='' ");}catch(Exception ignored){}}
 private void putFood(SQLiteDatabase d,String name,String cat,double cal,double p,double fat,double carbs,double fib){Cursor c=d.rawQuery("select id from foods where lower(name)=lower(?) limit 1",new String[]{name});boolean exists=c.moveToFirst();c.close();if(exists)return;ContentValues v=new ContentValues();v.put("name",name);v.put("brand","");v.put("categories",cat);v.put("cal",cal);v.put("protein",p);v.put("fat",fat);v.put("carbs",carbs);v.put("fiber",fib);v.put("sugar",0);d.insert("foods",null,v);}
 private void seedPoster(SQLiteDatabase d){try{
  Object[][] x={
   {"Blanc de poulet (sans peau)","Viandes",110,23.1,1.2,0,0},{"Blanc de dinde (sans peau)","Viandes",104,22.0,1.0,0,0},{"Bœuf extra maigre (filet)","Viandes",117,22.6,2.6,0,0},{"Veau (escalope)","Viandes",110,20.1,2.6,0,0},{"Lapin","Viandes",136,20.8,5.6,0,0},{"Porc filet mignon","Viandes",142,17.0,7.0,0,0},{"Agneau (gigot)","Viandes",166,18.6,10.0,0,0},{"Canard (viande avec peau)","Viandes",337,17.7,28.0,0,0},{"Magret de canard (sans peau)","Viandes",192,19.0,13.0,0,0},{"Porc (échine)","Viandes",263,15.0,21.0,0,0},
   {"Thon au naturel","Poissons & fruits de mer",116,25.0,1.0,0,0},{"Saumon","Poissons & fruits de mer",206,20.0,13.0,0,0},{"Truite","Poissons & fruits de mer",119,20.3,4.1,0,0},{"Cabillaud","Poissons & fruits de mer",84,18.0,0.7,0,0},{"Colin / Lieu noir","Poissons & fruits de mer",75,17.0,0.6,0,0},{"Crevettes cuites","Poissons & fruits de mer",99,23.0,0.9,0,0},{"Merlu","Poissons & fruits de mer",78,16.0,0.7,0,0},{"Sardine","Poissons & fruits de mer",208,25.0,11.5,0,0},{"Maquereau","Poissons & fruits de mer",205,19.0,13.5,0,0},{"Poisson pané (surgelé)","Poissons & fruits de mer",214,12.0,9.0,20.0,1.0},
   {"Œuf entier (1 œuf ~60 g)","Œufs & produits de la ferme",86,7.5,6.0,0.6,0},{"Blanc d'œuf (1 blanc ~33 g)","Œufs & produits de la ferme",17,3.6,0.1,0.2,0},{"Jaune d'œuf (1 jaune ~20 g)","Œufs & produits de la ferme",55,2.7,4.6,0.3,0},
   {"Skyr nature","Produits laitiers & fromages",62,10.5,0.2,3.6,0},{"Fromage blanc 0%","Produits laitiers & fromages",44,7.5,0.2,4.0,0},{"Yaourt nature","Produits laitiers & fromages",61,3.6,3.3,4.7,0},{"Mozzarella","Produits laitiers & fromages",280,22.0,20.0,2.2,0},{"Emmental","Produits laitiers & fromages",380,27.0,28.0,1.0,0},{"Parmesan","Produits laitiers & fromages",402,33.0,29.0,1.6,0},
   {"Épinards","Légumes",23,2.9,0.4,1.4,2.2},{"Brocoli","Légumes",34,2.8,0.4,4.1,2.6},{"Petits pois","Légumes",81,5.4,0.4,14.5,5.5},{"Haricots verts","Légumes",31,1.8,0.2,3.6,2.7},{"Pois chiches cuits","Légumes,Légumineuses",164,8.9,2.6,27.0,7.6},{"Lentilles cuites","Légumes,Légumineuses",116,9.0,0.4,20.0,7.9},{"Chou frisé (kale)","Légumes",49,4.3,0.9,8.8,4.1},{"Aubergine","Légumes",25,1.0,0.2,6.0,3.0},{"Courgette","Légumes",17,1.2,0.3,3.1,1.1},{"Carotte","Légumes",41,0.9,0.2,9.6,2.8},{"Patate douce cuite","Légumes,Féculents",90,1.6,0.1,20.7,3.0},{"Poivron rouge","Légumes",31,1.3,0.3,6.0,2.1},{"Tomate","Légumes",18,0.9,0.2,3.9,1.2},{"Oignon","Légumes",40,1.1,0.1,9.3,1.7},{"Concombre","Légumes",15,0.7,0.1,3.6,0.5},{"Ail","Légumes",149,6.4,0.5,33.1,2.1},{"Avocat (par fruit ~200 g)","Légumes,Fruits",322,4.0,29.0,17.0,13.5},
   {"Quinoa cuit","Féculents",120,4.4,1.9,21.3,2.8},{"Riz complet cuit","Féculents",112,2.6,0.9,23.5,1.8},{"Riz basmati cuit","Féculents",130,2.7,0.3,28.0,0.4},{"Pâtes complètes cuites","Féculents",134,5.6,1.1,25.0,3.8},{"Pâtes blanches cuites","Féculents",158,5.8,0.9,31.0,1.2},{"Boulgour cuit","Féculents",112,3.8,0.5,20.0,4.5},{"Semoule (couscous) cuite","Féculents",112,3.8,0.4,23.0,1.5},{"Pain complet","Féculents",247,9.0,3.2,41.0,6.7},{"Pain blanc","Féculents",265,8.5,3.2,49.0,2.7},{"Nouilles asiatiques (sèches)","Féculents",371,13.0,11.0,53.0,1.3},{"Nouilles instantanées (sèches)","Féculents",475,9.0,20.0,61.0,2.0},{"Pomme de terre cuite","Féculents",87,1.9,0.1,20.1,1.8},
   {"Banane","Fruits",89,1.1,0.3,22.8,2.6},{"Pomme","Fruits",52,0.3,0.2,13.8,2.4},{"Poire","Fruits",57,0.4,0.1,15.0,3.1},{"Fraise","Fruits",32,0.7,0.3,4.9,2.0},{"Myrtilles","Fruits",57,0.7,0.3,14.5,2.4},{"Framboises","Fruits",52,1.2,0.6,5.7,6.5},{"Pêche","Fruits",39,0.9,0.3,9.5,1.5},{"Clémentine","Fruits",47,0.8,0.2,11.8,1.7},{"Orange","Fruits",47,0.9,0.1,11.8,2.4},{"Pastèque","Fruits",30,0.6,0.2,7.6,0.4},{"Citron","Fruits",29,1.1,0.3,9.3,2.8},
   {"Huile d'olive","Matières grasses & cuisine",884,0,100,0,0},{"Huile de colza","Matières grasses & cuisine",884,0,100,0,0},{"Huile de tournesol","Matières grasses & cuisine",884,0,100,0,0},{"Beurre","Matières grasses & cuisine",717,0.6,81.0,0.6,0},{"Margarine","Matières grasses & cuisine",717,0.1,81.0,0.1,0},{"Crème fraîche entière","Matières grasses & cuisine",330,2.0,35.0,3.0,0},
   {"Sucre blanc","Desserts",400,0,0,100,0},{"Miel","Desserts",304,0.3,0,82.0,0.2},{"Glace Magnum Classic (~86 g)","Desserts",270,3.3,16.0,28.0,0.3},{"Glace à l'eau type Yeti (~65 g)","Desserts",45,0,0,11.0,0},{"Mousse au chocolat","Desserts",226,4.0,15.0,18.0,1.0},
   {"Saucisson sec","Apéritifs & boissons",467,25.0,40.0,1.5,0},{"Jambon cru","Apéritifs & boissons",241,27.0,14.0,1.5,0},{"Chips nature","Apéritifs & boissons",536,6.5,34.0,53.0,4.5},{"Olives vertes (~15 g / 5 pièces)","Apéritifs & boissons",140,1.0,15.0,3.0,2.5},{"Cacahuètes grillées","Apéritifs & boissons",567,25.0,49.0,16.0,8.5},{"Bière (25 cl)","Apéritifs & boissons",105,1.3,0,8.6,0},{"Vin rouge (15 cl)","Apéritifs & boissons",125,0,0,3.6,0},{"Rhum (4 cl)","Apéritifs & boissons",96,0,0,0,0},{"Jus d'orange (20 cl)","Apéritifs & boissons",90,1.6,0.2,20.0,0.5},{"Coca-Cola (20 cl)","Apéritifs & boissons",84,0,0,21.0,0}
  };
  for(Object[] a:x)putFood(d,(String)a[0],(String)a[1],((Number)a[2]).doubleValue(),((Number)a[3]).doubleValue(),((Number)a[4]).doubleValue(),((Number)a[5]).doubleValue(),((Number)a[6]).doubleValue());
 }catch(Exception ignored){}}
 private double gd(Cursor c,String s){return c.getDouble(c.getColumnIndexOrThrow(s));}private String gs(Cursor c,String s){return c.getString(c.getColumnIndexOrThrow(s));}
 public List<Profile> profiles(){ArrayList<Profile>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from profiles order by id",null);while(c.moveToNext())a.add(new Profile(c.getLong(0),gs(c,"name"),c.getInt(2),gd(c,"weight"),gd(c,"cal"),gd(c,"protein"),gd(c,"fat"),gd(c,"carbs"),gd(c,"fiber"),gd(c,"sugar")));c.close();return a;}
 public long saveProfile(Profile p){ContentValues v=new ContentValues();v.put("name",p.name);v.put("age",p.age);v.put("weight",p.weight);v.put("cal",p.cal);v.put("protein",p.protein);v.put("fat",p.fat);v.put("carbs",p.carbs);v.put("fiber",p.fiber);v.put("sugar",p.sugar);if(p.id==0)return getWritableDatabase().insert("profiles",null,v);getWritableDatabase().update("profiles",v,"id=?",new String[]{""+p.id});return p.id;}
 public List<Food> foods(){return foodsFiltered("","");}
 public List<Food> foodsFiltered(String query,String category){ArrayList<Food>a=new ArrayList<>();String q=query==null?"":query.trim();String cat=category==null?"":category.trim();String sql="select * from foods where 1=1";ArrayList<String> args=new ArrayList<>();if(!q.isEmpty()){for(String word:q.split("\\s+")){sql+=" and (lower(name) like ? or lower(brand) like ? or lower(categories) like ?)";String w="%"+word.toLowerCase(Locale.ROOT)+"%";args.add(w);args.add(w);args.add(w);}}if(!cat.isEmpty()&&!cat.equals("Toutes")){sql+=" and lower(categories) like ?";args.add("%"+cat.toLowerCase(Locale.ROOT)+"%");}sql+=" order by name collate nocase";Cursor c=getReadableDatabase().rawQuery(sql,args.toArray(new String[0]));while(c.moveToNext())a.add(new Food(c.getLong(c.getColumnIndexOrThrow("id")),gs(c,"name"),gs(c,"brand"),gs(c,"categories"),gd(c,"cal"),gd(c,"protein"),gd(c,"fat"),gd(c,"carbs"),gd(c,"fiber"),gd(c,"sugar")));c.close();return a;}
 public List<String> categories(){TreeSet<String>s=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);for(Food f:foods())for(String c:f.categories.split(","))if(!c.trim().isEmpty())s.add(c.trim());ArrayList<String>a=new ArrayList<>();a.add("Toutes");a.addAll(s);return a;}
 public long saveFood(Food f){ContentValues v=new ContentValues();v.put("name",f.name);v.put("brand",f.brand);v.put("categories",f.categories);v.put("cal",f.cal);v.put("protein",f.protein);v.put("fat",f.fat);v.put("carbs",f.carbs);v.put("fiber",f.fiber);v.put("sugar",f.sugar);return getWritableDatabase().insert("foods",null,v);}
 public void saveRecipe(String name,double portions,List<Ingredient> ins){Nutrients n=new Nutrients();for(Ingredient i:ins)n.add(new Nutrients(i.food.cal,i.food.protein,i.food.fat,i.food.carbs,i.food.fiber,i.food.sugar).scale(i.grams/100));double z=Math.max(1,portions);n=n.scale(1/z);ContentValues v=new ContentValues();v.put("name",name);v.put("portions",z);v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);getWritableDatabase().insert("recipes",null,v);}
 public List<Recipe> recipes(){ArrayList<Recipe>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from recipes order by name collate nocase",null);while(c.moveToNext()){Recipe r=new Recipe();r.id=c.getLong(0);r.name=gs(c,"name");r.portions=gd(c,"portions");r.cal=gd(c,"cal");r.protein=gd(c,"protein");r.fat=gd(c,"fat");r.carbs=gd(c,"carbs");r.fiber=gd(c,"fiber");r.sugar=gd(c,"sugar");a.add(r);}c.close();return a;}
 private ContentValues mealValues(long pid,String date,String time,String meal,String item,String amount,Nutrients n){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("time",time);v.put("meal",meal);v.put("item",item);v.put("amount",amount);v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);return v;}
 public long addMeal(long pid,String date,String time,String meal,String item,String amount,Nutrients n){return getWritableDatabase().insert("meals",null,mealValues(pid,date,time,meal,item,amount,n));}
 public void updateMeal(long id,long pid,String date,String time,String meal,String item,String amount,Nutrients n){getWritableDatabase().update("meals",mealValues(pid,date,time,meal,item,amount,n),"id=?",new String[]{""+id});}
 public void deleteMeal(long id){getWritableDatabase().delete("meals","id=?",new String[]{""+id});}
 public Nutrients totals(long pid,String date){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=?",new String[]{""+pid,date});c.moveToFirst();Nutrients n=new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5));c.close();return n;}
 public List<Meal> meals(long pid,String date){ArrayList<Meal>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from meals where profile_id=? and date=? order by time,id",new String[]{""+pid,date});while(c.moveToNext()){Meal m=new Meal();m.id=c.getLong(c.getColumnIndexOrThrow("id"));m.date=gs(c,"date");m.meal=gs(c,"meal");m.item=gs(c,"item");m.amount=gs(c,"amount");m.time=gs(c,"time");m.cal=gd(c,"cal");m.protein=gd(c,"protein");m.fat=gd(c,"fat");m.carbs=gd(c,"carbs");m.fiber=gd(c,"fiber");m.sugar=gd(c,"sugar");a.add(m);}c.close();return a;}
 public List<DayStat> stats(long pid,int days){ArrayList<DayStat>a=new ArrayList<>();LocalDate start=LocalDate.now().minusDays(days-1);for(int i=0;i<days;i++){DayStat s=new DayStat();s.date=start.plusDays(i).toString();s.n=totals(pid,s.date);a.add(s);}return a;}
 public List<HourStat> hourlyCumulative(long pid,String date){ArrayList<HourStat>a=new ArrayList<>();Nutrients running=new Nutrients();for(int h=0;h<=24;h++){if(h<24){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=? and cast(substr(time,1,2) as integer)=?",new String[]{""+pid,date,""+h});c.moveToFirst();running.add(new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5)));c.close();}HourStat s=new HourStat();s.hour=h;s.n=new Nutrients(running.cal,running.protein,running.fat,running.carbs,running.fiber,running.sugar);a.add(s);}return a;}
 public void saveWeight(long pid,String date,double weight){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("weight",weight);getWritableDatabase().insertWithOnConflict("weights",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public List<WeightLog> weights(long pid){ArrayList<WeightLog>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select date,weight from weights where profile_id=? order by date desc limit 30",new String[]{""+pid});while(c.moveToNext()){WeightLog w=new WeightLog();w.date=c.getString(0);w.weight=c.getDouble(1);a.add(w);}c.close();return a;}
}
