package com.appli.nutristat;

import android.database.sqlite.*;
import android.database.*;
import android.content.*;
import org.json.*;
import java.time.*;
import java.util.*;

public class NutriDb extends SQLiteOpenHelper {
 public static final int DB_VERSION=7;
 public static class Nutrients { public double cal,protein,fat,carbs,fiber,sugar; public Nutrients(){} public Nutrients(double a,double b,double c,double d,double e,double f){cal=a;protein=b;fat=c;carbs=d;fiber=e;sugar=f;} public Nutrients scale(double x){return new Nutrients(cal*x,protein*x,fat*x,carbs*x,fiber*x,sugar*x);} public void add(Nutrients n){cal+=n.cal;protein+=n.protein;fat+=n.fat;carbs+=n.carbs;fiber+=n.fiber;sugar+=n.sugar;} }
 public static class Profile { public long id; public String name; public int age; public double targetWeight,cal,protein,fat,carbs,fiber,sugar; public Profile(long id,String n,int a,double tw,double c,double p,double f,double g,double fi,double s){this.id=id;name=n;age=a;targetWeight=tw;cal=c;protein=p;fat=f;carbs=g;fiber=fi;sugar=s;} public String toString(){return name;} }
 public static class Food { public long id; public String name,brand,categories,basisUnit,defaultUnit,servingLabel; public double servingBase,cal,protein,fat,carbs,fiber,sugar; public int builtin,userModified; public String toString(){return name;} }
 public static class Recipe { public long id; public String name,categories; public double portions,cal,protein,fat,carbs,fiber,sugar; public int builtin,userModified; public String toString(){return name;} }
 public static class Ingredient { public long id,foodId; public String foodName; public double grams; public Food food; }
 public static class Meal { public long id; public String date,meal,item,amount,time,itemType,unit; public double quantity,cal,protein,fat,carbs,fiber,sugar; }
 public static class DayStat { public String date; public Nutrients n; }
 public static class HourStat { public int hour; public Nutrients n; }
 public static class WeightLog { public long id; public String date; public double weight; }
 public static class CatalogItem { public Food food; public Recipe recipe; public boolean isRecipe(){return recipe!=null;} public String name(){return isRecipe()?recipe.name:food.name;} }

 public NutriDb(Context c){super(c,"nutristat.db",null,DB_VERSION);}
 public void onCreate(SQLiteDatabase d){
  d.execSQL("create table profiles(id integer primary key,name text,age integer,target_weight real,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table foods(id integer primary key,name text,brand text,categories text,basis_unit text default 'g',default_unit text default 'g',serving_base real default 100,serving_label text default '',cal real,protein real,fat real,carbs real,fiber real,sugar real,builtin integer default 1,user_modified integer default 0)");
  d.execSQL("create table recipes(id integer primary key,name text,categories text default 'Plats',portions real default 1,cal real,protein real,fat real,carbs real,fiber real,sugar real,builtin integer default 0,user_modified integer default 0)");
  d.execSQL("create table recipe_items(id integer primary key,recipe_id integer,food_id integer,grams real)");
  d.execSQL("create table meals(id integer primary key,profile_id integer,date text,time text,meal text,item text,item_type text default 'food',quantity real default 0,unit text default 'g',amount text,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table weights(id integer primary key,profile_id integer,date text,weight real)");
  d.execSQL("insert into profiles(name,age,target_weight,cal,protein,fat,carbs,fiber,sugar) values('Utilisateur',30,70,2000,120,70,230,30,50)");
  seedAll(d);
 }
 public void onUpgrade(SQLiteDatabase d,int oldV,int newV){ensureSchema(d);migrateNames(d);seedAll(d);}
 public void onOpen(SQLiteDatabase d){super.onOpen(d);if(!d.isReadOnly()){ensureSchema(d);migrateNames(d);seedAll(d);}}
 private boolean hasColumn(SQLiteDatabase d,String table,String col){Cursor c=null;try{c=d.rawQuery("pragma table_info("+table+")",null);while(c.moveToNext())if(col.equalsIgnoreCase(c.getString(c.getColumnIndexOrThrow("name"))))return true;}catch(Exception ignored){}finally{if(c!=null)c.close();}return false;}
 private void addCol(SQLiteDatabase d,String table,String def){String col=def.split(" ")[0];try{if(!hasColumn(d,table,col))d.execSQL("alter table "+table+" add column "+def);}catch(Exception ignored){}}
 private void ensureSchema(SQLiteDatabase d){
  addCol(d,"profiles","target_weight real default 70"); if(hasColumn(d,"profiles","weight"))try{d.execSQL("update profiles set target_weight=weight where target_weight is null");}catch(Exception ignored){}
  addCol(d,"foods","categories text default ''"); addCol(d,"foods","basis_unit text default 'g'"); addCol(d,"foods","default_unit text default 'g'"); addCol(d,"foods","serving_base real default 100"); addCol(d,"foods","serving_label text default ''"); addCol(d,"foods","builtin integer default 1"); addCol(d,"foods","user_modified integer default 0");
  addCol(d,"recipes","categories text default 'Plats'"); addCol(d,"recipes","builtin integer default 0"); addCol(d,"recipes","user_modified integer default 0");
  try{d.execSQL("create table if not exists recipe_items(id integer primary key,recipe_id integer,food_id integer,grams real)");}catch(Exception ignored){}
  addCol(d,"meals","time text default '12:00'"); addCol(d,"meals","item_type text default 'food'"); addCol(d,"meals","quantity real default 0"); addCol(d,"meals","unit text default 'g'");
  try{d.execSQL("update meals set time='12:00' where time is null or trim(time)='' ");}catch(Exception ignored){}
 }
 private void migrateNames(SQLiteDatabase d){
  String[][] ren={{"Olives vertes (~15 g / 5 pièces)","Olives vertes"},{"Bière (25 cl)","Bière"},{"Vin rouge (15 cl)","Vin rouge"},{"Rhum (4 cl)","Rhum"},{"Jus d'orange (20 cl)","Jus d'orange"},{"Coca-Cola (20 cl)","Coca-Cola"},{"Œuf entier (1 œuf ~60 g)","Œuf entier"},{"Blanc d'œuf (1 blanc ~33 g)","Blanc d'œuf"},{"Jaune d'œuf (1 jaune ~20 g)","Jaune d'œuf"},{"Avocat (par fruit ~200 g)","Avocat"},{"Glace Magnum Classic (~86 g)","Glace Magnum Classic"},{"Glace à l'eau type Yeti (~65 g)","Glace à l'eau type Yeti"}};
  for(String[] r:ren)try{ContentValues v=new ContentValues();v.put("name",r[1]);d.update("foods",v,"name=?",new String[]{r[0]});}catch(Exception ignored){}
  try{d.execSQL("update foods set categories=replace(categories,'Apéritifs & boissons','Apéritifs') where categories like '%Apéritifs & boissons%' and name not in ('Bière','Vin rouge','Rhum','Jus d''orange','Coca-Cola')");}catch(Exception ignored){}
  for(String n:new String[]{"Bière","Vin rouge","Rhum","Jus d'orange","Coca-Cola"})try{ContentValues v=new ContentValues();v.put("categories","Boissons");v.put("basis_unit","ml");v.put("default_unit","cL");d.update("foods",v,"name=?",new String[]{n});}catch(Exception ignored){}
 }
 private ContentValues foodValues(String name,String brand,String cats,String basis,String defUnit,double servingBase,String servingLabel,double cal,double p,double fat,double carbs,double fib,double sugar,int builtin,int modified){ContentValues v=new ContentValues();v.put("name",name);v.put("brand",brand);v.put("categories",cats);v.put("basis_unit",basis);v.put("default_unit",defUnit);v.put("serving_base",servingBase);v.put("serving_label",servingLabel);v.put("cal",cal);v.put("protein",p);v.put("fat",fat);v.put("carbs",carbs);v.put("fiber",fib);v.put("sugar",sugar);v.put("builtin",builtin);v.put("user_modified",modified);return v;}
 private void putFood(SQLiteDatabase d,String name,String cats,String basis,String defUnit,double servingBase,String servingLabel,double cal,double p,double fat,double carbs,double fib,double sugar){Cursor c=d.rawQuery("select id,user_modified from foods where lower(name)=lower(?) limit 1",new String[]{name});if(c.moveToFirst()){long id=c.getLong(0);int mod=c.getInt(1);c.close();if(mod==0)d.update("foods",foodValues(name,"",cats,basis,defUnit,servingBase,servingLabel,cal,p,fat,carbs,fib,sugar,1,0),"id=?",new String[]{""+id});return;}c.close();d.insert("foods",null,foodValues(name,"",cats,basis,defUnit,servingBase,servingLabel,cal,p,fat,carbs,fib,sugar,1,0));}
 private void seedAll(SQLiteDatabase d){try{
  Object[][] x={
   {"Blanc de poulet","Viandes","g","g",150,"1 portion ≈ 150 g",110,23.1,1.2,0,0,0},{"Blanc de dinde","Viandes","g","g",150,"1 escalope ≈ 150 g",104,22,1,0,0,0},{"Bœuf extra maigre","Viandes","g","g",120,"1 steak/filet ≈ 120 g",117,22.6,2.6,0,0,0},{"Steak haché 5%","Viandes","g","g",125,"1 steak ≈ 125 g",137,21,5,0,0,0},{"Veau","Viandes","g","g",150,"1 escalope ≈ 150 g",110,20.1,2.6,0,0,0},{"Lapin","Viandes","g","g",150,"1 portion ≈ 150 g",136,20.8,5.6,0,0,0},{"Porc filet mignon","Viandes","g","g",150,"1 portion ≈ 150 g",142,17,7,0,0,0},{"Agneau","Viandes","g","g",150,"1 tranche de gigot ≈ 150 g",166,18.6,10,0,0,0},{"Magret de canard","Viandes","g","g",160,"1 demi-magret ≈ 160 g",192,19,13,0,0,0},{"Jambon blanc","Viandes","g","g",45,"1 tranche ≈ 45 g",116,20,4,1,0,1},{"Jambon cru","Apéritifs","g","g",30,"2 tranches ≈ 30 g",241,27,14,1.5,0,0},{"Lardons","Viandes","g","g",50,"1 petite portion ≈ 50 g",280,17,23,1,0,0},
   {"Thon au naturel","Poissons & fruits de mer","g","g",140,"1 boîte égouttée ≈ 140 g",116,25,1,0,0,0},{"Saumon","Poissons & fruits de mer","g","g",150,"1 pavé ≈ 150 g",206,20,13,0,0,0},{"Truite","Poissons & fruits de mer","g","g",150,"1 filet ≈ 150 g",119,20.3,4.1,0,0,0},{"Cabillaud","Poissons & fruits de mer","g","g",150,"1 filet ≈ 150 g",84,18,.7,0,0,0},{"Crevettes cuites","Poissons & fruits de mer","g","g",100,"1 portion ≈ 100 g",99,23,.9,0,0,0},
   {"Œuf entier","Œufs","g","portion",60,"1 œuf ≈ 60 g",143,12.6,9.5,.7,0,.4},{"Blanc d'œuf","Œufs","g","portion",33,"1 blanc ≈ 33 g",52,11,.2,.7,0,.7},{"Jaune d'œuf","Œufs","g","portion",20,"1 jaune ≈ 20 g",275,13.5,23,1.5,0,.5},
   {"Skyr nature","Produits laitiers","g","g",150,"1 pot ≈ 150 g",62,10.5,.2,3.6,0,3.6},{"Yaourt nature","Produits laitiers","g","portion",125,"1 pot ≈ 125 g",61,3.6,3.3,4.7,0,4.7},{"Fromage blanc 0%","Produits laitiers","g","g",150,"1 bol ≈ 150 g",44,7.5,.2,4,0,4},{"Mozzarella","Produits laitiers","g","g",125,"1 boule ≈ 125 g",280,22,20,2.2,0,1},{"Emmental","Produits laitiers","g","g",30,"1 portion ≈ 30 g",380,27,28,1,0,0},{"Parmesan","Produits laitiers","g","g",15,"1 c. à soupe râpée ≈ 15 g",402,33,29,1.6,0,0},{"Lait demi-écrémé","Produits laitiers,Boissons","ml","cL",250,"1 verre ≈ 25 cL",46,3.2,1.6,4.8,0,4.8},{"Crème fraîche entière","Produits laitiers,Matières grasses","g","g",30,"2 c. à soupe ≈ 30 g",330,2,35,3,0,3},{"Mascarpone","Produits laitiers","g","g",50,"1 portion ≈ 50 g",429,4.6,42,4.8,0,4.8},
   {"Brocoli","Légumes","g","g",150,"1 portion ≈ 150 g",34,2.8,.4,4.1,2.6,1.7},{"Épinards","Légumes","g","g",150,"1 portion ≈ 150 g",23,2.9,.4,1.4,2.2,.4},{"Haricots verts","Légumes","g","g",150,"1 portion ≈ 150 g",31,1.8,.2,3.6,2.7,1.4},{"Petits pois","Légumes","g","g",120,"1 portion ≈ 120 g",81,5.4,.4,14.5,5.5,5.7},{"Pois chiches cuits","Légumineuses","g","g",150,"1 portion ≈ 150 g",164,8.9,2.6,27,7.6,4.8},{"Lentilles cuites","Légumineuses","g","g",150,"1 portion ≈ 150 g",116,9,.4,20,7.9,1.8},{"Haricots rouges cuits","Légumineuses","g","g",150,"1 portion ≈ 150 g",127,8.7,.5,22.8,6.4,.3},{"Aubergine","Légumes","g","g",250,"1 aubergine moyenne ≈ 250 g",25,1,.2,6,3,3.5},{"Courgette","Légumes","g","g",200,"1 courgette moyenne ≈ 200 g",17,1.2,.3,3.1,1.1,2.5},{"Carotte","Légumes","g","g",100,"1 carotte moyenne ≈ 100 g",41,.9,.2,9.6,2.8,4.7},{"Poivron rouge","Légumes","g","g",150,"1 poivron moyen ≈ 150 g",31,1.3,.3,6,2.1,4.2},{"Tomate","Légumes","g","g",120,"1 tomate moyenne ≈ 120 g",18,.9,.2,3.9,1.2,2.6},{"Oignon","Légumes","g","g",100,"1 oignon moyen ≈ 100 g",40,1.1,.1,9.3,1.7,4.2},{"Concombre","Légumes","g","g",300,"1 concombre moyen ≈ 300 g",15,.7,.1,3.6,.5,1.7},{"Ail","Légumes","g","g",5,"1 gousse ≈ 5 g",149,6.4,.5,33.1,2.1,1},{"Salade verte","Légumes","g","g",80,"1 portion ≈ 80 g",15,1.4,.2,2.9,1.3,.8},{"Avocat","Fruits,Légumes","g","portion",200,"1 avocat moyen ≈ 200 g",161,2,14.5,8.5,6.7,.7},{"Pomme de terre cuite","Féculents","g","g",180,"1 pomme de terre moyenne ≈ 180 g",87,1.9,.1,20.1,1.8,.9},
   {"Riz basmati cuit","Féculents","g","g",150,"1 portion cuite ≈ 150 g",130,2.7,.3,28,.4,.1},{"Riz complet cuit","Féculents","g","g",150,"1 portion cuite ≈ 150 g",112,2.6,.9,23.5,1.8,.4},{"Pâtes blanches cuites","Féculents","g","g",180,"1 portion cuite ≈ 180 g",158,5.8,.9,31,1.2,.6},{"Pâtes complètes cuites","Féculents","g","g",180,"1 portion cuite ≈ 180 g",134,5.6,1.1,25,3.8,1},{"Quinoa cuit","Féculents","g","g",150,"1 portion cuite ≈ 150 g",120,4.4,1.9,21.3,2.8,.9},{"Semoule cuite","Féculents","g","g",150,"1 portion cuite ≈ 150 g",112,3.8,.4,23,1.5,.1},{"Pain complet","Féculents","g","g",40,"1 tranche ≈ 40 g",247,9,3.2,41,6.7,5},{"Pain blanc","Féculents","g","g",30,"1 tranche ≈ 30 g",265,8.5,3.2,49,2.7,5},{"Farine de blé","Féculents","g","g",30,"2 c. à soupe ≈ 30 g",364,10.3,1,76.3,2.7,.3},{"Feuilles de lasagnes","Féculents","g","g",75,"1 portion sèche ≈ 75 g",350,12,2,70,3,3},{"Sauce tomate","Légumes","g","g",125,"1 petite louche ≈ 125 g",35,1.5,.3,6,1.5,4},{"Chapelure","Féculents","g","g",15,"1 c. à soupe ≈ 15 g",395,13,5,72,4.5,6},
   {"Banane","Fruits","g","portion",120,"1 banane moyenne ≈ 120 g",89,1.1,.3,22.8,2.6,12.2},{"Pomme","Fruits","g","portion",150,"1 pomme moyenne ≈ 150 g",52,.3,.2,13.8,2.4,10.4},{"Poire","Fruits","g","portion",170,"1 poire moyenne ≈ 170 g",57,.4,.1,15,3.1,9.8},{"Orange","Fruits","g","portion",180,"1 orange moyenne ≈ 180 g",47,.9,.1,11.8,2.4,9.4},{"Clémentine","Fruits","g","portion",75,"1 clémentine ≈ 75 g",47,.8,.2,11.8,1.7,9.2},{"Fraise","Fruits","g","g",150,"1 bol ≈ 150 g",32,.7,.3,4.9,2,4.9},{"Myrtilles","Fruits","g","g",125,"1 barquette ≈ 125 g",57,.7,.3,14.5,2.4,10},{"Framboises","Fruits","g","g",125,"1 barquette ≈ 125 g",52,1.2,.6,5.7,6.5,4.4},{"Pêche","Fruits","g","portion",150,"1 pêche moyenne ≈ 150 g",39,.9,.3,9.5,1.5,8.4},{"Citron","Fruits","g","portion",100,"1 citron ≈ 100 g",29,1.1,.3,9.3,2.8,2.5},
   {"Huile d'olive","Matières grasses","g","càc",5,"1 c. à café ≈ 5 g",884,0,100,0,0,0},{"Huile de colza","Matières grasses","g","càc",5,"1 c. à café ≈ 5 g",884,0,100,0,0,0},{"Huile de tournesol","Matières grasses","g","càc",5,"1 c. à café ≈ 5 g",884,0,100,0,0,0},{"Beurre","Matières grasses","g","g",10,"1 noisette ≈ 10 g",717,.6,81,.6,0,.1},{"Sucre blanc","Desserts","g","g",5,"1 c. à café ≈ 5 g",400,0,0,100,0,100},{"Miel","Desserts","g","g",15,"1 c. à soupe ≈ 15 g",304,.3,0,82,.2,82},{"Chocolat noir","Desserts","g","g",20,"2 carrés ≈ 20 g",546,4.9,31,61,7,48},{"Levure chimique","Desserts","g","g",11,"1 sachet ≈ 11 g",53,0,0,28,0,0},{"Café préparé","Boissons","ml","cL",100,"1 tasse ≈ 10 cL",2,.1,0,0,0,0},
   {"Saucisson sec","Apéritifs","g","g",30,"6 rondelles ≈ 30 g",467,25,40,1.5,0,.5},{"Chips nature","Apéritifs","g","g",30,"1 petite poignée ≈ 30 g",536,6.5,34,53,4.5,.5},{"Olives vertes","Apéritifs","g","portion",15,"5 olives ≈ 15 g",140,1,15,3,2.5,.5},{"Cacahuètes grillées","Apéritifs","g","g",30,"1 poignée ≈ 30 g",567,25,49,16,8.5,4},
   {"Bière","Boissons","ml","cL",250,"1 demi/verre ≈ 25 cL",42,.5,0,3.4,0,.1},{"Vin rouge","Boissons","ml","cL",150,"1 verre ≈ 15 cL",83,0,0,2.4,0,.6},{"Rhum","Boissons","ml","cL",40,"1 dose ≈ 4 cL",240,0,0,0,0,0},{"Jus d'orange","Boissons","ml","cL",200,"1 verre ≈ 20 cL",45,.8,.1,10,.2,8.4},{"Coca-Cola","Boissons","ml","cL",200,"1 verre ≈ 20 cL",42,0,0,10.6,0,10.6}
  };
  for(Object[] a:x)putFood(d,(String)a[0],(String)a[1],(String)a[2],(String)a[3],((Number)a[4]).doubleValue(),(String)a[5],((Number)a[6]).doubleValue(),((Number)a[7]).doubleValue(),((Number)a[8]).doubleValue(),((Number)a[9]).doubleValue(),((Number)a[10]).doubleValue(),((Number)a[11]).doubleValue());
  seedRecipes(d);
 }catch(Exception ignored){}}
 private long foodId(SQLiteDatabase d,String name){Cursor c=d.rawQuery("select id from foods where lower(name)=lower(?) limit 1",new String[]{name});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
 private int countRecipeItems(SQLiteDatabase d,long rid){Cursor c=d.rawQuery("select count(*) from recipe_items where recipe_id=?",new String[]{""+rid});c.moveToFirst();int n=c.getInt(0);c.close();return n;}
 private void insertRecipeItems(SQLiteDatabase d,long rid,Object[][] items){for(Object[] it:items){long fid=foodId(d,(String)it[0]);if(fid>0){ContentValues v=new ContentValues();v.put("recipe_id",rid);v.put("food_id",fid);v.put("grams",((Number)it[1]).doubleValue());d.insert("recipe_items",null,v);}}}
 private void seedRecipe(SQLiteDatabase d,String name,String cat,int portions,Object[][] items){Cursor q=d.rawQuery("select id,user_modified from recipes where lower(name)=lower(?)",new String[]{name});if(q.moveToFirst()){long id=q.getLong(0);int mod=q.getInt(1);q.close();if(mod==0&&countRecipeItems(d,id)==0)insertRecipeItems(d,id,items);if(mod==0)recalcRecipe(d,id);return;}q.close();ContentValues v=new ContentValues();v.put("name",name);v.put("categories",cat);v.put("portions",portions);v.put("builtin",1);v.put("user_modified",0);long id=d.insert("recipes",null,v);insertRecipeItems(d,id,items);recalcRecipe(d,id);}
 private void seedRecipes(SQLiteDatabase d){
  seedRecipe(d,"Gâteau au yaourt","Desserts",8,new Object[][]{{"Yaourt nature",125},{"Farine de blé",240},{"Sucre blanc",160},{"Œuf entier",180},{"Huile de tournesol",60},{"Levure chimique",11}});
  seedRecipe(d,"Spaghetti bolognaise","Plats",4,new Object[][]{{"Pâtes blanches cuites",720},{"Steak haché 5%",400},{"Sauce tomate",500},{"Oignon",100},{"Ail",10},{"Huile d'olive",10}});
  seedRecipe(d,"Pâtes carbonara","Plats",4,new Object[][]{{"Pâtes blanches cuites",720},{"Lardons",200},{"Crème fraîche entière",200},{"Parmesan",60},{"Œuf entier",120}});
  seedRecipe(d,"Salade César","Plats",4,new Object[][]{{"Blanc de poulet",500},{"Salade verte",320},{"Pain blanc",120},{"Parmesan",60},{"Huile d'olive",30}});
  seedRecipe(d,"Lasagnes bolognaises","Plats",6,new Object[][]{{"Feuilles de lasagnes",450},{"Steak haché 5%",500},{"Sauce tomate",600},{"Oignon",120},{"Mozzarella",250},{"Parmesan",60}});
  seedRecipe(d,"Quiche lorraine","Plats",6,new Object[][]{{"Farine de blé",200},{"Beurre",100},{"Lardons",200},{"Œuf entier",180},{"Crème fraîche entière",250},{"Emmental",100}});
  seedRecipe(d,"Croque-monsieur","Plats",1,new Object[][]{{"Pain blanc",60},{"Jambon blanc",45},{"Emmental",30},{"Beurre",5}});
  seedRecipe(d,"Omelette au fromage","Plats",1,new Object[][]{{"Œuf entier",180},{"Emmental",30},{"Beurre",5}});
  seedRecipe(d,"Poulet curry et riz","Plats",4,new Object[][]{{"Blanc de poulet",600},{"Riz basmati cuit",600},{"Crème fraîche entière",120},{"Oignon",100},{"Huile d'olive",10}});
  seedRecipe(d,"Chili con carne","Plats",4,new Object[][]{{"Steak haché 5%",400},{"Haricots rouges cuits",500},{"Sauce tomate",400},{"Oignon",100},{"Riz basmati cuit",400}});
  seedRecipe(d,"Hachis parmentier","Plats",6,new Object[][]{{"Steak haché 5%",600},{"Pomme de terre cuite",900},{"Lait demi-écrémé",200},{"Beurre",30},{"Emmental",80}});
  seedRecipe(d,"Gratin dauphinois","Plats",6,new Object[][]{{"Pomme de terre cuite",1200},{"Crème fraîche entière",300},{"Lait demi-écrémé",300},{"Emmental",120},{"Ail",10}});
  seedRecipe(d,"Ratatouille","Plats",4,new Object[][]{{"Aubergine",300},{"Courgette",300},{"Tomate",400},{"Poivron rouge",200},{"Oignon",120},{"Huile d'olive",20}});
  seedRecipe(d,"Couscous poulet","Plats",6,new Object[][]{{"Semoule cuite",900},{"Blanc de poulet",700},{"Pois chiches cuits",300},{"Courgette",300},{"Carotte",300},{"Tomate",300}});
  seedRecipe(d,"Riz cantonais","Plats",4,new Object[][]{{"Riz basmati cuit",600},{"Petits pois",200},{"Œuf entier",180},{"Jambon blanc",180},{"Huile de tournesol",10}});
  seedRecipe(d,"Crêpes","Desserts",10,new Object[][]{{"Farine de blé",250},{"Lait demi-écrémé",500},{"Œuf entier",180},{"Beurre",30},{"Sucre blanc",30}});
  seedRecipe(d,"Mousse au chocolat","Desserts",6,new Object[][]{{"Chocolat noir",200},{"Œuf entier",240},{"Sucre blanc",30}});
  seedRecipe(d,"Tiramisu","Desserts",6,new Object[][]{{"Mascarpone",500},{"Œuf entier",240},{"Sucre blanc",100},{"Café préparé",200},{"Chocolat noir",30}});
  seedRecipe(d,"Brownie au chocolat","Desserts",8,new Object[][]{{"Chocolat noir",200},{"Beurre",150},{"Sucre blanc",150},{"Farine de blé",80},{"Œuf entier",180}});
  seedRecipe(d,"Salade de fruits","Desserts",4,new Object[][]{{"Pomme",150},{"Banane",120},{"Orange",180},{"Poire",170},{"Fraise",150}});
 }
 private double gd(Cursor c,String s){int i=c.getColumnIndex(s);return i<0||c.isNull(i)?0:c.getDouble(i);} private int gi(Cursor c,String s){int i=c.getColumnIndex(s);return i<0||c.isNull(i)?0:c.getInt(i);} private String gs(Cursor c,String s){int i=c.getColumnIndex(s);return i<0||c.isNull(i)?"":c.getString(i);}
 public List<Profile> profiles(){ArrayList<Profile>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from profiles order by id",null);while(c.moveToNext())a.add(new Profile(c.getLong(c.getColumnIndexOrThrow("id")),gs(c,"name"),gi(c,"age"),gd(c,"target_weight"),gd(c,"cal"),gd(c,"protein"),gd(c,"fat"),gd(c,"carbs"),gd(c,"fiber"),gd(c,"sugar")));c.close();return a;}
 public long saveProfile(Profile p){ContentValues v=new ContentValues();v.put("name",p.name);v.put("age",p.age);v.put("target_weight",p.targetWeight);v.put("cal",p.cal);v.put("protein",p.protein);v.put("fat",p.fat);v.put("carbs",p.carbs);v.put("fiber",p.fiber);v.put("sugar",p.sugar);if(p.id==0)return getWritableDatabase().insert("profiles",null,v);getWritableDatabase().update("profiles",v,"id=?",new String[]{""+p.id});return p.id;}
 private Food foodFrom(Cursor c){Food f=new Food();f.id=c.getLong(c.getColumnIndexOrThrow("id"));f.name=gs(c,"name");f.brand=gs(c,"brand");f.categories=gs(c,"categories");f.basisUnit=gs(c,"basis_unit");f.defaultUnit=gs(c,"default_unit");f.servingBase=gd(c,"serving_base");f.servingLabel=gs(c,"serving_label");f.cal=gd(c,"cal");f.protein=gd(c,"protein");f.fat=gd(c,"fat");f.carbs=gd(c,"carbs");f.fiber=gd(c,"fiber");f.sugar=gd(c,"sugar");f.builtin=gi(c,"builtin");f.userModified=gi(c,"user_modified");return f;}
 public Food food(long id){Cursor c=getReadableDatabase().rawQuery("select * from foods where id=?",new String[]{""+id});Food f=c.moveToFirst()?foodFrom(c):null;c.close();return f;} public Food foodByName(String name){Cursor c=getReadableDatabase().rawQuery("select * from foods where lower(name)=lower(?) limit 1",new String[]{name});Food f=c.moveToFirst()?foodFrom(c):null;c.close();return f;}
 public List<Food> foods(){return foodsFiltered("","");}
 public List<Food> foodsFiltered(String q,String cat){ArrayList<Food>a=new ArrayList<>();String sql="select * from foods where 1=1";ArrayList<String> args=new ArrayList<>();q=q==null?"":q.trim();cat=cat==null?"":cat.trim();if(!q.isEmpty())for(String w:q.split("\\s+")){sql+=" and (lower(name) like ? or lower(categories) like ?)";String x="%"+w.toLowerCase(Locale.ROOT)+"%";args.add(x);args.add(x);}if(!cat.isEmpty()&&!cat.equals("Toutes")&&!cat.equals("Recettes")){sql+=" and lower(categories) like ?";args.add("%"+cat.toLowerCase(Locale.ROOT)+"%");}sql+=" order by name collate nocase";Cursor c=getReadableDatabase().rawQuery(sql,args.toArray(new String[0]));while(c.moveToNext())a.add(foodFrom(c));c.close();return a;}
 public long saveFood(Food f,boolean modified){ContentValues v=foodValues(f.name,f.brand,f.categories,f.basisUnit,f.defaultUnit,f.servingBase,f.servingLabel,f.cal,f.protein,f.fat,f.carbs,f.fiber,f.sugar,f.builtin,modified?1:f.userModified);if(f.id==0){v.put("builtin",0);v.put("user_modified",1);return getWritableDatabase().insert("foods",null,v);}getWritableDatabase().update("foods",v,"id=?",new String[]{""+f.id});return f.id;} public void deleteFood(long id){getWritableDatabase().delete("foods","id=?",new String[]{""+id});}
 public Nutrients forServing(Food f){return new Nutrients(f.cal,f.protein,f.fat,f.carbs,f.fiber,f.sugar).scale(f.servingBase/100.0);} public Nutrients nutrientsFor(Food f,double qty,String unit){double factor;if("portion".equals(unit)||"càc".equals(unit))factor=qty*f.servingBase/100.0;else if("cL".equals(unit))factor=qty*10.0/100.0;else factor=qty/100.0;return new Nutrients(f.cal,f.protein,f.fat,f.carbs,f.fiber,f.sugar).scale(factor);}
 public List<String> categories(){TreeSet<String>s=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);for(Food f:foods())for(String c:f.categories.split(","))if(!c.trim().isEmpty())s.add(c.trim());ArrayList<String>a=new ArrayList<>();a.add("Toutes");a.add("Recettes");a.addAll(s);return a;}
 private Recipe recipeFrom(Cursor c){Recipe r=new Recipe();r.id=c.getLong(c.getColumnIndexOrThrow("id"));r.name=gs(c,"name");r.categories=gs(c,"categories");r.portions=gd(c,"portions");r.cal=gd(c,"cal");r.protein=gd(c,"protein");r.fat=gd(c,"fat");r.carbs=gd(c,"carbs");r.fiber=gd(c,"fiber");r.sugar=gd(c,"sugar");r.builtin=gi(c,"builtin");r.userModified=gi(c,"user_modified");return r;}
 public List<Recipe> recipes(){return recipesFiltered("");} public List<Recipe> recipesFiltered(String q){ArrayList<Recipe>a=new ArrayList<>();q=q==null?"":q.trim();Cursor c=q.isEmpty()?getReadableDatabase().rawQuery("select * from recipes order by name collate nocase",null):getReadableDatabase().rawQuery("select * from recipes where lower(name) like ? or lower(categories) like ? order by name collate nocase",new String[]{"%"+q.toLowerCase(Locale.ROOT)+"%","%"+q.toLowerCase(Locale.ROOT)+"%"});while(c.moveToNext())a.add(recipeFrom(c));c.close();return a;}
 public Recipe recipe(long id){Cursor c=getReadableDatabase().rawQuery("select * from recipes where id=?",new String[]{""+id});Recipe r=c.moveToFirst()?recipeFrom(c):null;c.close();return r;}
 public List<Ingredient> recipeIngredients(long rid){ArrayList<Ingredient>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select ri.id,ri.food_id,ri.grams,f.name from recipe_items ri join foods f on f.id=ri.food_id where ri.recipe_id=? order by ri.id",new String[]{""+rid});while(c.moveToNext()){Ingredient i=new Ingredient();i.id=c.getLong(0);i.foodId=c.getLong(1);i.grams=c.getDouble(2);i.foodName=c.getString(3);i.food=food(i.foodId);a.add(i);}c.close();return a;}
 public long saveRecipe(Recipe r,List<Ingredient> items){ContentValues v=new ContentValues();v.put("name",r.name);v.put("categories",r.categories);v.put("portions",Math.max(1,r.portions));v.put("builtin",r.id==0?0:r.builtin);v.put("user_modified",1);SQLiteDatabase d=getWritableDatabase();long id=r.id;if(id==0)id=d.insert("recipes",null,v);else d.update("recipes",v,"id=?",new String[]{""+id});d.delete("recipe_items","recipe_id=?",new String[]{""+id});for(Ingredient i:items){ContentValues iv=new ContentValues();iv.put("recipe_id",id);iv.put("food_id",i.food!=null?i.food.id:i.foodId);iv.put("grams",i.grams);d.insert("recipe_items",null,iv);}recalcRecipe(d,id);return id;} public void deleteRecipe(long id){SQLiteDatabase d=getWritableDatabase();d.delete("recipe_items","recipe_id=?",new String[]{""+id});d.delete("recipes","id=?",new String[]{""+id});}
 private void recalcRecipe(SQLiteDatabase d,long rid){Cursor rc=d.rawQuery("select portions from recipes where id=?",new String[]{""+rid});if(!rc.moveToFirst()){rc.close();return;}double portions=Math.max(1,rc.getDouble(0));rc.close();Cursor c=d.rawQuery("select f.cal,f.protein,f.fat,f.carbs,f.fiber,f.sugar,ri.grams from recipe_items ri join foods f on f.id=ri.food_id where ri.recipe_id=?",new String[]{""+rid});Nutrients n=new Nutrients();while(c.moveToNext())n.add(new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5)).scale(c.getDouble(6)/100));c.close();n=n.scale(1.0/portions);ContentValues v=new ContentValues();v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);d.update("recipes",v,"id=?",new String[]{""+rid});}
 public List<CatalogItem> catalog(String q,String cat,String type){ArrayList<CatalogItem>a=new ArrayList<>();boolean foods=!"Recette".equals(type)&&!"Recettes".equals(cat);boolean recs=!"Aliment".equals(type)&&(cat==null||cat.equals("Toutes")||cat.equals("Recettes"));if(foods)for(Food f:foodsFiltered(q,cat)){CatalogItem x=new CatalogItem();x.food=f;a.add(x);}if(recs)for(Recipe r:recipesFiltered(q)){CatalogItem x=new CatalogItem();x.recipe=r;a.add(x);}Collections.sort(a,(x,y)->x.name().compareToIgnoreCase(y.name()));return a;}
 private ContentValues mealValues(long pid,String date,String time,String meal,String item,String itemType,double quantity,String unit,String amount,Nutrients n){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("time",time);v.put("meal",meal);v.put("item",item);v.put("item_type",itemType);v.put("quantity",quantity);v.put("unit",unit);v.put("amount",amount);v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);return v;}
 public long addMeal(long pid,String date,String time,String meal,String item,String itemType,double quantity,String unit,Nutrients n){String amount=String.format(Locale.FRANCE,"%.1f %s",quantity,unit);return getWritableDatabase().insert("meals",null,mealValues(pid,date,time,meal,item,itemType,quantity,unit,amount,n));} public void updateMeal(long id,long pid,String date,String time,String meal,String item,String itemType,double quantity,String unit,Nutrients n){getWritableDatabase().update("meals",mealValues(pid,date,time,meal,item,itemType,quantity,unit,String.format(Locale.FRANCE,"%.1f %s",quantity,unit),n),"id=?",new String[]{""+id});} public void deleteMeal(long id){getWritableDatabase().delete("meals","id=?",new String[]{""+id});}
 public List<Meal> meals(long pid,String date){ArrayList<Meal>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from meals where profile_id=? and date=? order by time,id",new String[]{""+pid,date});while(c.moveToNext()){Meal m=new Meal();m.id=c.getLong(c.getColumnIndexOrThrow("id"));m.date=gs(c,"date");m.time=gs(c,"time");m.meal=gs(c,"meal");m.item=gs(c,"item");m.itemType=gs(c,"item_type");m.quantity=gd(c,"quantity");m.unit=gs(c,"unit");m.amount=gs(c,"amount");m.cal=gd(c,"cal");m.protein=gd(c,"protein");m.fat=gd(c,"fat");m.carbs=gd(c,"carbs");m.fiber=gd(c,"fiber");m.sugar=gd(c,"sugar");a.add(m);}c.close();return a;}
 public Nutrients totals(long pid,String date){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=?",new String[]{""+pid,date});c.moveToFirst();Nutrients n=new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5));c.close();return n;}
 public List<DayStat> stats(long pid,int days){ArrayList<DayStat>a=new ArrayList<>();LocalDate start=LocalDate.now().minusDays(days-1);for(int i=0;i<days;i++){DayStat s=new DayStat();s.date=start.plusDays(i).toString();s.n=totals(pid,s.date);a.add(s);}return a;}
 public List<HourStat> hourlyCumulative(long pid,String date){ArrayList<HourStat>a=new ArrayList<>();Nutrients run=new Nutrients();for(int h=0;h<=24;h++){if(h<24){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=? and cast(substr(time,1,2) as integer)=?",new String[]{""+pid,date,""+h});c.moveToFirst();run.add(new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5)));c.close();}HourStat s=new HourStat();s.hour=h;s.n=new Nutrients(run.cal,run.protein,run.fat,run.carbs,run.fiber,run.sugar);a.add(s);}return a;}
 public long saveWeight(long pid,String date,double w){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("weight",w);return getWritableDatabase().insert("weights",null,v);} public void updateWeight(long id,String date,double w){ContentValues v=new ContentValues();v.put("date",date);v.put("weight",w);getWritableDatabase().update("weights",v,"id=?",new String[]{""+id});} public void deleteWeight(long id){getWritableDatabase().delete("weights","id=?",new String[]{""+id});}
 public List<WeightLog> weights(long pid){ArrayList<WeightLog>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select id,date,weight from weights where profile_id=? order by date",new String[]{""+pid});while(c.moveToNext()){WeightLog w=new WeightLog();w.id=c.getLong(0);w.date=c.getString(1);w.weight=c.getDouble(2);a.add(w);}c.close();return a;} public List<WeightLog> weightsSince(long pid,LocalDate since){ArrayList<WeightLog>a=new ArrayList<>();for(WeightLog w:weights(pid))if(since==null||!LocalDate.parse(w.date).isBefore(since))a.add(w);return a;}
 public JSONObject exportProfile(long pid)throws JSONException{Profile p=null;for(Profile x:profiles())if(x.id==pid)p=x;if(p==null)throw new JSONException("Profil introuvable");JSONObject root=new JSONObject();root.put("format","nutristat-profile");root.put("version",1);JSONObject po=new JSONObject();po.put("name",p.name);po.put("age",p.age);po.put("targetWeight",p.targetWeight);po.put("cal",p.cal);po.put("protein",p.protein);po.put("fat",p.fat);po.put("carbs",p.carbs);po.put("fiber",p.fiber);po.put("sugar",p.sugar);root.put("profile",po);JSONArray ma=new JSONArray();Cursor mc=getReadableDatabase().rawQuery("select * from meals where profile_id=? order by date,time,id",new String[]{""+pid});while(mc.moveToNext()){JSONObject o=new JSONObject();for(String k:new String[]{"date","time","meal","item","item_type","unit","amount"})o.put(k,gs(mc,k));for(String k:new String[]{"quantity","cal","protein","fat","carbs","fiber","sugar"})o.put(k,gd(mc,k));ma.put(o);}mc.close();root.put("meals",ma);JSONArray wa=new JSONArray();for(WeightLog w:weights(pid)){JSONObject o=new JSONObject();o.put("date",w.date);o.put("weight",w.weight);wa.put(o);}root.put("weights",wa);JSONArray fa=new JSONArray();Cursor fc=getReadableDatabase().rawQuery("select * from foods where builtin=0 or user_modified=1 order by name",null);while(fc.moveToNext()){Food f=foodFrom(fc);JSONObject o=new JSONObject();o.put("name",f.name);o.put("brand",f.brand);o.put("categories",f.categories);o.put("basisUnit",f.basisUnit);o.put("defaultUnit",f.defaultUnit);o.put("servingBase",f.servingBase);o.put("servingLabel",f.servingLabel);o.put("cal",f.cal);o.put("protein",f.protein);o.put("fat",f.fat);o.put("carbs",f.carbs);o.put("fiber",f.fiber);o.put("sugar",f.sugar);fa.put(o);}fc.close();root.put("foods",fa);JSONArray ra=new JSONArray();Cursor rc=getReadableDatabase().rawQuery("select * from recipes where builtin=0 or user_modified=1 order by name",null);while(rc.moveToNext()){Recipe r=recipeFrom(rc);JSONObject o=new JSONObject();o.put("name",r.name);o.put("categories",r.categories);o.put("portions",r.portions);JSONArray ia=new JSONArray();for(Ingredient i:recipeIngredients(r.id)){JSONObject io=new JSONObject();io.put("food",i.foodName);io.put("grams",i.grams);ia.put(io);}o.put("ingredients",ia);ra.put(o);}rc.close();root.put("recipes",ra);return root;}
 public void importProfile(long pid,JSONObject root)throws JSONException{if(!"nutristat-profile".equals(root.optString("format")))throw new JSONException("Fichier Nutristat invalide");SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{JSONObject po=root.getJSONObject("profile");saveProfile(new Profile(pid,po.optString("name","Utilisateur"),po.optInt("age",30),po.optDouble("targetWeight",70),po.optDouble("cal",2000),po.optDouble("protein",120),po.optDouble("fat",70),po.optDouble("carbs",230),po.optDouble("fiber",30),po.optDouble("sugar",50)));JSONArray fa=root.optJSONArray("foods");if(fa!=null)for(int j=0;j<fa.length();j++){JSONObject o=fa.getJSONObject(j);Food f=foodByName(o.getString("name"));if(f==null){f=new Food();f.id=0;f.builtin=0;}f.name=o.getString("name");f.brand=o.optString("brand","");f.categories=o.optString("categories","");f.basisUnit=o.optString("basisUnit","g");f.defaultUnit=o.optString("defaultUnit","g");f.servingBase=o.optDouble("servingBase",100);f.servingLabel=o.optString("servingLabel","");f.cal=o.optDouble("cal",0);f.protein=o.optDouble("protein",0);f.fat=o.optDouble("fat",0);f.carbs=o.optDouble("carbs",0);f.fiber=o.optDouble("fiber",0);f.sugar=o.optDouble("sugar",0);saveFood(f,true);}JSONArray ra=root.optJSONArray("recipes");if(ra!=null)for(int j=0;j<ra.length();j++){JSONObject o=ra.getJSONObject(j);Recipe r=null;for(Recipe x:recipes())if(x.name.equalsIgnoreCase(o.getString("name")))r=x;if(r==null){r=new Recipe();r.id=0;r.builtin=0;}r.name=o.getString("name");r.categories=o.optString("categories","Plats");r.portions=o.optDouble("portions",1);ArrayList<Ingredient> its=new ArrayList<>();JSONArray ia=o.optJSONArray("ingredients");if(ia!=null)for(int k=0;k<ia.length();k++){JSONObject io=ia.getJSONObject(k);Food f=foodByName(io.getString("food"));if(f!=null){Ingredient i=new Ingredient();i.food=f;i.foodId=f.id;i.foodName=f.name;i.grams=io.optDouble("grams",0);its.add(i);}}saveRecipe(r,its);}d.delete("meals","profile_id=?",new String[]{""+pid});d.delete("weights","profile_id=?",new String[]{""+pid});JSONArray ma=root.optJSONArray("meals");if(ma!=null)for(int j=0;j<ma.length();j++){JSONObject o=ma.getJSONObject(j);Nutrients nn=new Nutrients(o.optDouble("cal"),o.optDouble("protein"),o.optDouble("fat"),o.optDouble("carbs"),o.optDouble("fiber"),o.optDouble("sugar"));addMeal(pid,o.optString("date"),o.optString("time","12:00"),o.optString("meal"),o.optString("item"),o.optString("item_type","food"),o.optDouble("quantity",0),o.optString("unit","g"),nn);}JSONArray wa=root.optJSONArray("weights");if(wa!=null)for(int j=0;j<wa.length();j++){JSONObject o=wa.getJSONObject(j);saveWeight(pid,o.optString("date"),o.optDouble("weight"));}d.setTransactionSuccessful();}finally{d.endTransaction();}}
}
