package com.appli.nutristat;
import android.database.sqlite.*;import android.database.*;import android.content.*;import java.time.*;import java.util.*;
public class NutriDb extends SQLiteOpenHelper{
 public static class Nutrients{public double cal,protein,fat,carbs,fiber,sugar;public Nutrients(){}public Nutrients(double a,double b,double c,double d,double e,double f){cal=a;protein=b;fat=c;carbs=d;fiber=e;sugar=f;}public Nutrients scale(double x){return new Nutrients(cal*x,protein*x,fat*x,carbs*x,fiber*x,sugar*x);}public void add(Nutrients n){cal+=n.cal;protein+=n.protein;fat+=n.fat;carbs+=n.carbs;fiber+=n.fiber;sugar+=n.sugar;}}
 public static class Profile{public long id;public String name;public int age;public double weight,cal,protein,fat,carbs,fiber,sugar;public Profile(long id,String n,int a,double w,double c,double p,double f,double g,double fi,double s){this.id=id;name=n;age=a;weight=w;cal=c;protein=p;fat=f;carbs=g;fiber=fi;sugar=s;}public String toString(){return name;}}
 public static class Food{public long id;public String name,brand,categories;public double cal,protein,fat,carbs,fiber,sugar;public Food(long id,String n,String b,String cats,double c,double p,double f,double g,double fi,double s){this.id=id;name=n;brand=b;categories=cats==null?"":cats;cal=c;protein=p;fat=f;carbs=g;fiber=fi;sugar=s;}public String toString(){return name;}}
 public static class Recipe{public long id;public String name;public double portions,cal,protein,fat,carbs,fiber,sugar;public String toString(){return name;}}
 public static class Ingredient{public Food food;public double grams;public Ingredient(Food f,double g){food=f;grams=g;}}
 public static class Meal{public String meal,item,amount,time;public double cal;}
 public static class DayStat{public String date;public Nutrients n;}
 public static class HourStat{public int hour;public Nutrients n;}
 public static class WeightLog{public String date;public double weight;}
 public NutriDb(Context c){super(c,"nutristat.db",null,2);}
 public void onCreate(SQLiteDatabase d){
  d.execSQL("create table profiles(id integer primary key,name text,age integer,weight real,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table foods(id integer primary key,name text,brand text,categories text,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table recipes(id integer primary key,name text,portions real,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table meals(id integer primary key,profile_id integer,date text,time text,meal text,item text,amount text,cal real,protein real,fat real,carbs real,fiber real,sugar real)");
  d.execSQL("create table weights(id integer primary key,profile_id integer,date text,weight real,unique(profile_id,date))");
  d.execSQL("insert into profiles values(1,'Utilisateur',30,70,2000,120,70,230,30,50)");
  String[] seed={
   "('Poulet, blanc','','Viandes',165,31,3.6,0,0,0)","('Riz blanc cuit','','Féculents',130,2.7,0.3,28,0.4,0.1)","('Œuf entier','','Œufs,Protéines',143,12.6,9.5,0.7,0,0.4)","('Banane','','Fruits',89,1.1,0.3,22.8,2.6,12.2)","('Pomme','','Fruits',52,0.3,0.2,13.8,2.4,10.4)","('Flocons d''avoine','','Féculents,Petit-déjeuner',389,16.9,6.9,66.3,10.6,0.9)","('Lait demi-écrémé','','Produits laitiers',46,3.2,1.6,4.8,0,4.8)","('Yaourt nature','','Produits laitiers,Desserts',61,3.5,3.3,4.7,0,4.7)","('Huile d''olive','','Matières grasses',884,0,100,0,0,0)","('Brocoli cuit','','Légumes',35,2.4,0.4,7.2,3.3,1.4)"};
  for(String s:seed)d.execSQL("insert into foods(name,brand,categories,cal,protein,fat,carbs,fiber,sugar) values"+s);
 }
 public void onUpgrade(SQLiteDatabase d,int o,int n){if(o<2){d.execSQL("alter table foods add column categories text default ''");d.execSQL("alter table meals add column time text default '12:00'");String[][] x={{"Poulet, blanc","Viandes"},{"Riz blanc cuit","Féculents"},{"Œuf entier","Œufs,Protéines"},{"Banane","Fruits"},{"Pomme","Fruits"},{"Flocons d'avoine","Féculents,Petit-déjeuner"},{"Lait demi-écrémé","Produits laitiers"},{"Yaourt nature","Produits laitiers,Desserts"},{"Huile d'olive","Matières grasses"},{"Brocoli cuit","Légumes"}};for(String[] a:x){ContentValues v=new ContentValues();v.put("categories",a[1]);d.update("foods",v,"name=?",new String[]{a[0]});}}}
 private double gd(Cursor c,String s){return c.getDouble(c.getColumnIndexOrThrow(s));}private String gs(Cursor c,String s){return c.getString(c.getColumnIndexOrThrow(s));}
 public List<Profile> profiles(){ArrayList<Profile>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from profiles order by id",null);while(c.moveToNext())a.add(new Profile(c.getLong(0),gs(c,"name"),c.getInt(2),gd(c,"weight"),gd(c,"cal"),gd(c,"protein"),gd(c,"fat"),gd(c,"carbs"),gd(c,"fiber"),gd(c,"sugar")));c.close();return a;}
 public long saveProfile(Profile p){ContentValues v=new ContentValues();v.put("name",p.name);v.put("age",p.age);v.put("weight",p.weight);v.put("cal",p.cal);v.put("protein",p.protein);v.put("fat",p.fat);v.put("carbs",p.carbs);v.put("fiber",p.fiber);v.put("sugar",p.sugar);if(p.id==0)return getWritableDatabase().insert("profiles",null,v);getWritableDatabase().update("profiles",v,"id=?",new String[]{""+p.id});return p.id;}
 public List<Food> foods(){return foodsFiltered("","");}
 public List<Food> foodsFiltered(String query,String category){ArrayList<Food>a=new ArrayList<>();String q=query==null?"":query.trim();String cat=category==null?"":category.trim();String sql="select * from foods where 1=1";ArrayList<String> args=new ArrayList<>();if(!q.isEmpty()){sql+=" and (lower(name) like ? or lower(brand) like ?)";args.add("%"+q.toLowerCase(Locale.ROOT)+"%");args.add("%"+q.toLowerCase(Locale.ROOT)+"%");}if(!cat.isEmpty()&&!cat.equals("Toutes")){sql+=" and lower(categories) like ?";args.add("%"+cat.toLowerCase(Locale.ROOT)+"%");}sql+=" order by name";Cursor c=getReadableDatabase().rawQuery(sql,args.toArray(new String[0]));while(c.moveToNext())a.add(new Food(c.getLong(c.getColumnIndexOrThrow("id")),gs(c,"name"),gs(c,"brand"),gs(c,"categories"),gd(c,"cal"),gd(c,"protein"),gd(c,"fat"),gd(c,"carbs"),gd(c,"fiber"),gd(c,"sugar")));c.close();return a;}
 public List<String> categories(){TreeSet<String>s=new TreeSet<>();for(Food f:foods())for(String c:f.categories.split(","))if(!c.trim().isEmpty())s.add(c.trim());ArrayList<String>a=new ArrayList<>();a.add("Toutes");a.addAll(s);return a;}
 public long saveFood(Food f){ContentValues v=new ContentValues();v.put("name",f.name);v.put("brand",f.brand);v.put("categories",f.categories);v.put("cal",f.cal);v.put("protein",f.protein);v.put("fat",f.fat);v.put("carbs",f.carbs);v.put("fiber",f.fiber);v.put("sugar",f.sugar);return getWritableDatabase().insert("foods",null,v);}
 public void saveRecipe(String name,double portions,List<Ingredient> ins){Nutrients n=new Nutrients();for(Ingredient i:ins)n.add(new Nutrients(i.food.cal,i.food.protein,i.food.fat,i.food.carbs,i.food.fiber,i.food.sugar).scale(i.grams/100));double z=Math.max(1,portions);n=n.scale(1/z);ContentValues v=new ContentValues();v.put("name",name);v.put("portions",z);v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);getWritableDatabase().insert("recipes",null,v);}
 public List<Recipe> recipes(){ArrayList<Recipe>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from recipes order by name",null);while(c.moveToNext()){Recipe r=new Recipe();r.id=c.getLong(0);r.name=gs(c,"name");r.portions=gd(c,"portions");r.cal=gd(c,"cal");r.protein=gd(c,"protein");r.fat=gd(c,"fat");r.carbs=gd(c,"carbs");r.fiber=gd(c,"fiber");r.sugar=gd(c,"sugar");a.add(r);}c.close();return a;}
 public void addMeal(long pid,String date,String time,String meal,String item,String amount,Nutrients n){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("time",time);v.put("meal",meal);v.put("item",item);v.put("amount",amount);v.put("cal",n.cal);v.put("protein",n.protein);v.put("fat",n.fat);v.put("carbs",n.carbs);v.put("fiber",n.fiber);v.put("sugar",n.sugar);getWritableDatabase().insert("meals",null,v);}
 public Nutrients totals(long pid,String date){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=?",new String[]{""+pid,date});c.moveToFirst();Nutrients n=new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5));c.close();return n;}
 public List<Meal> meals(long pid,String date){ArrayList<Meal>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select * from meals where profile_id=? and date=? order by time,id",new String[]{""+pid,date});while(c.moveToNext()){Meal m=new Meal();m.meal=gs(c,"meal");m.item=gs(c,"item");m.amount=gs(c,"amount");m.time=gs(c,"time");m.cal=gd(c,"cal");a.add(m);}c.close();return a;}
 public List<DayStat> stats(long pid,int days){ArrayList<DayStat>a=new ArrayList<>();LocalDate start=LocalDate.now().minusDays(days-1);for(int i=0;i<days;i++){DayStat s=new DayStat();s.date=start.plusDays(i).toString();s.n=totals(pid,s.date);a.add(s);}return a;}
 public List<HourStat> hourlyCumulative(long pid,String date){ArrayList<HourStat>a=new ArrayList<>();Nutrients running=new Nutrients();for(int h=0;h<=24;h++){if(h<24){Cursor c=getReadableDatabase().rawQuery("select coalesce(sum(cal),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),coalesce(sum(fiber),0),coalesce(sum(sugar),0) from meals where profile_id=? and date=? and cast(substr(time,1,2) as integer)=?",new String[]{""+pid,date,""+h});c.moveToFirst();running.add(new Nutrients(c.getDouble(0),c.getDouble(1),c.getDouble(2),c.getDouble(3),c.getDouble(4),c.getDouble(5)));c.close();}HourStat s=new HourStat();s.hour=h;s.n=new Nutrients(running.cal,running.protein,running.fat,running.carbs,running.fiber,running.sugar);a.add(s);}return a;}
 public void saveWeight(long pid,String date,double weight){ContentValues v=new ContentValues();v.put("profile_id",pid);v.put("date",date);v.put("weight",weight);getWritableDatabase().insertWithOnConflict("weights",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public List<WeightLog> weights(long pid){ArrayList<WeightLog>a=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("select date,weight from weights where profile_id=? order by date desc limit 30",new String[]{""+pid});while(c.moveToNext()){WeightLog w=new WeightLog();w.date=c.getString(0);w.weight=c.getDouble(1);a.add(w);}c.close();return a;}
}
